ccflags-y += -Idrivers/media/platform/msm/camera_v2-ef71
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ef71/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ef71/msm_vb2
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ef71/camera
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ef71/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ef71/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += cci/ io/ csiphy/ csid/ actuator/ eeprom/ ois/ flash/
obj-$(CONFIG_MSM_CAMERA_SENSOR) += msm_sensor_init.o msm_sensor_driver.o msm_sensor.o
