ccflags-y += -Idrivers/media/platform/msm/camera_v2-ef71
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ef71/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ef71/sensor/io
obj-$(CONFIG_MSM_CSID) += msm_ispif.o
