ccflags-y += -Idrivers/media/platform/msm/camera_v2-ef71
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ef71/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ef71/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ef71/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
