#ifndef _EF67_MXT_CFG_
#define _EF67_MXT_CFG_

#define MXT_REFERENCE_MIN		    22000
#define MXT_REFERENCE_MAX		    28000
#define MXT_MAX_Y_CHANNEL			20
#define MXT_USED_Y_CHANNEL			17


// define ITO_TYPE_CHECK


/*--------------- DEFINITION TOUCH MODE --------------------------------*/
/* Screen resolution */
#define SCREEN_RESOLUTION_X					1079
#define SCREEN_RESOLUTION_SCREEN_Y			1919
#define SCREEN_RESOLUTION_TOUCHKEY_Y		185
#define SCREEN_RESOLUTION_WHOLE_Y			(SCREEN_RESOLUTION_SCREEN_Y + SCREEN_RESOLUTION_TOUCHKEY_Y)

#if PAN_HAVE_TOUCH_KEY
#define PAN_1ST_TOUCH_KEY_X				    215
#define PAN_2ND_TOUCH_KEY_X				    540
#define PAN_3RD_TOUCH_KEY_X				    865
#define PAN_TOUCH_KEY_Y					      2050

#define PAN_1ST_TOUCH_KEY_MARGIN_X		65
#define PAN_2ND_TOUCH_KEY_MARGIN_X		125
#define PAN_3RD_TOUCH_KEY_MARGIN_X		65

#define PAN_1ST_TOUCH_KEY_TYPE			  KEY_BACK
#define PAN_2ND_TOUCH_KEY_TYPE			  KEY_HOMEPAGE
#define PAN_3RD_TOUCH_KEY_TYPE			  KEY_MENU

#define PAN_TOUCH_KEY_MARGIN_Y			  65	
#endif


static gen_powerconfig_t7_config_t obj_power_config_t7[TOUCH_MODE_MAX_NUM] = {
	{
		.idleacqint  = 255,	
		.actvacqint  = 255,	
		.actv2idleto = 50,	
		.cfg         = 3,
		.cfg2		 = 0,
	},
	{
		.idleacqint  = 255,	
		.actvacqint  = 255,	
		.actv2idleto = 50,	
		.cfg         = 3,
		.cfg2		 = 0,
	},
	{
		.idleacqint  = 255,	
		.actvacqint  = 255,	
		.actv2idleto = 50,	
		.cfg         = 3,
		.cfg2		 = 0,
	},
	{
		.idleacqint  = 255,	
		.actvacqint  = 255,	
		.actv2idleto = 50,	
		.cfg         = 3,
		.cfg2		 = 0,
	},
};

static gen_acquisitionconfig_t8_config_t obj_acquisition_config_t8[TOUCH_MODE_MAX_NUM] = {
	{
		.chrgtime        = 40, 
		.atchdrift       = 0,              
		.tchdrift        = 5,  		
		.driftst         = 1, 		
		.tchautocal      = 0,  	
		.sync		     = 0,   				
		.atchcalst       = 5, 	
		.atchcalsthr     = 0,       
		.atchfrccalthr   = 100,      	
		.atchfrccalratio = (-100),      	
		.measallow		 = 3,     		
		.measidledef     = 1,  		
		.measactivedef   = 1, 
		.refmode		 = 1,
		.cfg			 = 0,
	},
	{
		.chrgtime        = 40, 
		.atchdrift       = 0,              
		.tchdrift        = 5,  		
		.driftst         = 1, 		
		.tchautocal      = 0,  	
		.sync		     = 0,   				
		.atchcalst       = 5, 	
		.atchcalsthr     = 0,       
		.atchfrccalthr   = 100,      	
		.atchfrccalratio = (-100),      	
		.measallow		 = 3,     		
		.measidledef     = 1,  		
		.measactivedef   = 1, 
		.refmode		 = 1,
		.cfg			 = 0,
	},
	{
		.chrgtime        = 40, 
		.atchdrift       = 0,              
		.tchdrift        = 5,  		
		.driftst         = 1, 		
		.tchautocal      = 0,  	
		.sync		     = 0,   				
		.atchcalst       = 5, 	
		.atchcalsthr     = 0,       
		.atchfrccalthr   = 100,      	
		.atchfrccalratio = (-100),      	
		.measallow		 = 3,     		
		.measidledef     = 1,  		
		.measactivedef   = 1, 
		.refmode		 = 1,
		.cfg			 = 0,
	},
	{
		.chrgtime        = 40, 
		.atchdrift       = 0,              
		.tchdrift        = 5,  		
		.driftst         = 1, 		
		.tchautocal      = 0,  	
		.sync		     = 0,   				
		.atchcalst       = 5, 	
		.atchcalsthr     = 0,       
		.atchfrccalthr   = 100,      	
		.atchfrccalratio = (-100),      	
		.measallow		 = 3,     		
		.measidledef     = 1,  		
		.measactivedef   = 1, 
		.refmode		 = 1,
		.cfg			 = 0,
	},
};

static touch_keyarray_t15_config_t obj_key_array_t15[TOUCH_MODE_MAX_NUM] = {
	{
		.ctrl        = 0, 			
		.xorigin     = 0, 		
		.yorigin     = 0,		
		.xsize       = 0, 			
		.ysize       = 0, 			
		.akscfg      = 0, 		
		.blen        = 0, 			
		.tchthr      = 0, 		
		.tchdi       = 0, 			
		.tchhyst	 = 0, 
		.reserved	 = 0, 
	},
	{
		.ctrl        = 0, 			
		.xorigin     = 0, 		
		.yorigin     = 0,		
		.xsize       = 0, 			
		.ysize       = 0, 			
		.akscfg      = 0, 		
		.blen        = 0, 			
		.tchthr      = 0, 		
		.tchdi       = 0, 			
		.tchhyst	 = 0, 
		.reserved	 = 0, 
	},
	{
		.ctrl        = 0, 			
		.xorigin     = 0, 		
		.yorigin     = 0,		
		.xsize       = 0, 			
		.ysize       = 0, 			
		.akscfg      = 0, 		
		.blen        = 0, 			
		.tchthr      = 0, 		
		.tchdi       = 0, 			
		.tchhyst	 = 0, 
		.reserved	 = 0, 
	},
	{
		.ctrl        = 0, 			
		.xorigin     = 0, 		
		.yorigin     = 0,		
		.xsize       = 0, 			
		.ysize       = 0, 			
		.akscfg      = 0, 		
		.blen        = 0, 			
		.tchthr      = 0, 		
		.tchdi       = 0, 			
		.tchhyst	 = 0, 
		.reserved	 = 0, 
	},
};

static spt_commsconfig_t18_config_t obj_comm_config_t18[TOUCH_MODE_MAX_NUM] = {
	{
		.ctrl = 0,
		.cmd  = 0, 
	},
	{
		.ctrl = 0,
		.cmd  = 0, 
	},
	{
		.ctrl = 0,
		.cmd  = 0, 
	},
	{
		.ctrl = 0,
		.cmd  = 0, 
	},
};

static spt_gpiopwm_t19_config_t obj_gpiopwm_config_t19[TOUCH_MODE_MAX_NUM] = {
	{
		.ctrl       = 0, 
		.reportmask = 0, 
		.dir        = 0, 
		.intpullup  = 0, 
		.out        = 0, 
		.wake       = 0,
	},
	{
		.ctrl       = 0, 
		.reportmask = 0, 
		.dir        = 0, 
		.intpullup  = 0, 
		.out        = 0, 
		.wake       = 0,
	},
	{
		.ctrl       = 0, 
		.reportmask = 0, 
		.dir        = 0, 
		.intpullup  = 0, 
		.out        = 0, 
		.wake       = 0,
	},
	{
		.ctrl       = 0, 
		.reportmask = 0, 
		.dir        = 0, 
		.intpullup  = 0, 
		.out        = 0, 
		.wake       = 0,
	},
};

static spt_selftest_t25_config_t obj_self_test_t25[TOUCH_MODE_MAX_NUM] = {
	{
		.ctrl               = 0,     					
		.cmd                = 0,     			
#if NUM_OF_TOUCH_OBJECTS
		.siglim[0].upsiglim = 0,         		
		.siglim[0].losiglim = 0,         		
		.siglim[1].upsiglim = 0,          		
		.siglim[1].losiglim = 0,            		
#endif
		.pindwellus         = 0,     					
#if NUM_OF_TOUCH_OBJECTS
		.sigrangelim[0]     = 0,     					
		.sigrangelim[1]     = 0,     					
#endif
	},
	{
		.ctrl               = 0,     					
		.cmd                = 0,     			
#if NUM_OF_TOUCH_OBJECTS
		.siglim[0].upsiglim = 0,         		
		.siglim[0].losiglim = 0,         		
		.siglim[1].upsiglim = 0,          		
		.siglim[1].losiglim = 0,            		
#endif
		.pindwellus         = 0,     					
#if NUM_OF_TOUCH_OBJECTS
		.sigrangelim[0]     = 0,     					
		.sigrangelim[1]     = 0,     					
#endif
	},
	{
		.ctrl               = 0,     					
		.cmd                = 0,     			
#if NUM_OF_TOUCH_OBJECTS
		.siglim[0].upsiglim = 0,         		
		.siglim[0].losiglim = 0,         		
		.siglim[1].upsiglim = 0,          		
		.siglim[1].losiglim = 0,            		
#endif
		.pindwellus         = 0,     					
#if NUM_OF_TOUCH_OBJECTS
		.sigrangelim[0]     = 0,     					
		.sigrangelim[1]     = 0,     					
#endif
	},
	{
		.ctrl               = 0,     					
		.cmd                = 0,     			
#if NUM_OF_TOUCH_OBJECTS
		.siglim[0].upsiglim = 0,         		
		.siglim[0].losiglim = 0,         		
		.siglim[1].upsiglim = 0,          		
		.siglim[1].losiglim = 0,            		
#endif
		.pindwellus         = 0,     					
#if NUM_OF_TOUCH_OBJECTS
		.sigrangelim[0]     = 0,     					
		.sigrangelim[1]     = 0,     					
#endif
	},
};

static proci_gripsuppression_t40_config_t obj_grip_suppression_t40[TOUCH_MODE_MAX_NUM] = {
	{
		.ctrl    = 1, 					
		.xlogrip = 0,          	
		.xhigrip = 0,         	
		.ylogrip = 15,             	
		.yhigrip = 15, 				
	},
	{
		.ctrl    = 1, 					
		.xlogrip = 0,          	
		.xhigrip = 0,         	
		.ylogrip = 15,             	
		.yhigrip = 15, 				
	},
	{
		.ctrl    = 17, 					
		.xlogrip = 0,          	
		.xhigrip = 0,         	
		.ylogrip = 15,             	
		.yhigrip = 15, 				
	},
	{
		.ctrl    = 17, 					
		.xlogrip = 0,          	
		.xhigrip = 0,         	
		.ylogrip = 15,             	
		.yhigrip = 15, 				
	},
};

static proci_touchsuppression_t42_config_t obj_touch_suppression_t42[TOUCH_MODE_MAX_NUM] = {
	{ 
		.ctrl          = 1,  
		.apprthr	   = 150, 
		.maxapprarea   = 80,  
		.maxtcharea    = 120, 
		.supstrength   = 255, 
		.supextto      = 200, 
		.maxnumtchs    = 0,  
		.shapestrength = 31,   
		.supdist       = 1,  
		.disthyst      = 1,  
		.maxscrnarea   = 0,
		.cfg           = 0,
		.maxfngrsarea  = 0,
	},
	{ 
		.ctrl          = 1,  
		.apprthr	   = 150, 
		.maxapprarea   = 80,  
		.maxtcharea    = 120, 
		.supstrength   = 255, 
		.supextto      = 200, 
		.maxnumtchs    = 0,  
		.shapestrength = 31,   
		.supdist       = 1,  
		.disthyst      = 1,  
		.maxscrnarea   = 0,
		.cfg           = 0,
		.maxfngrsarea  = 0,
	},
	{ 
		.ctrl          = 119,  
		.apprthr	   = 1, 
		.maxapprarea   = 20,  
		.maxtcharea    = 20, 
		.supstrength   = 65, 
		.supextto      = 0, 
		.maxnumtchs    = 0,  
		.shapestrength = 25,   
		.supdist       = 1,  
		.disthyst      = 1,  
		.maxscrnarea   = 0,
		.cfg           = 0,
		.maxfngrsarea  = 0,
	},
	{ 
		.ctrl          = 119,  
		.apprthr	   = 1, 
		.maxapprarea   = 20,  
		.maxtcharea    = 20, 
		.supstrength   = 65, 
		.supextto      = 0, 
		.maxnumtchs    = 0,  
		.shapestrength = 25,   
		.supdist       = 1,  
		.disthyst      = 1,  
		.maxscrnarea   = 0,
		.cfg           = 0,
		.maxfngrsarea  = 0,
	},
};

static spt_cteconfig_t46_config_t obj_cte_config_t46[TOUCH_MODE_MAX_NUM] = {
	{
		.ctrl          = 4,	 	
		.mode    	   = 0,	  
		.idlesyncsperx = 32, 				
		.actvsyncsperx = 32, 				
		.adcspersync   = 0,  				
		.pulsesperadc  = 0,  			
		.xslew         = 0,  				
		.syncdelay     = 0,						
		.xvoltage      = 0,				
		.adcctrl	   = 0,
		.reserved	   = 0,	 
	},
	{
		.ctrl          = 4,	 	
		.mode    	   = 0,	  
		.idlesyncsperx = 32, 				
		.actvsyncsperx = 52, 				
		.adcspersync   = 0,  				
		.pulsesperadc  = 0,  			
		.xslew         = 0,  				
		.syncdelay     = 0,						
		.xvoltage      = 0,				
		.adcctrl	   = 0,
		.reserved	   = 0,	 
	},
	{
		.ctrl          = 4,	 	
		.mode    	   = 0,	  
		.idlesyncsperx = 16, 				
		.actvsyncsperx = 32, 				
		.adcspersync   = 0,  				
		.pulsesperadc  = 0,  			
		.xslew         = 0,  				
		.syncdelay     = 0,						
		.xvoltage      = 0,				
		.adcctrl	   = 0,
		.reserved	   = 0,	 
	},
	{
		.ctrl          = 4,	 	
		.mode    	   = 0,	  
		.idlesyncsperx = 16, 				
		.actvsyncsperx = 32, 				
		.adcspersync   = 0,  				
		.pulsesperadc  = 0,  			
		.xslew         = 0,  				
		.syncdelay     = 0,						
		.xvoltage      = 0,				
		.adcctrl	   = 0,
		.reserved	   = 0,	 
	},
};

static proci_stylus_t47_config_t obj_stylus_t47[TOUCH_MODE_MAX_NUM] = {
	{	
		.ctrl       = 0,   				
		.contmin    = 35,  					
		.contmax    = 40,  					
		.stability  = 255, 				
		.maxtcharea = 3,            		
		.amplthr    = 30,  					
		.styshape   = 10, 				
		.hoversup   = 180, 					
		.confthr    = 1,   					
		.syncsperx  = 40,  					
		.xposadj    = 0,  					
		.yposadj    = 0,  				
		.cfg        = 3,   
		.reserved[0]  = 0,                    
		.reserved[1]  = 0,                    
		.reserved[2]  = 0,                 
		.reserved[3]  = 0,                    
		.reserved[4]  = 0,                   
		.reserved[5]  = 0,                    
		.reserved[6]  = 0,                    
		.supstyto   = 1,                    
		.maxnumsty  = 0,                    
		.xedgectrl  = 0, 					
		.xedgedist  = 0, 				
		.yedgectrl  = 0, 					
		.yedgedist  = 0,  
		.supto		= 0,
		.supclassmode = 0,
	},
	{	
		.ctrl       = 9,   				
		.contmin    = 35,  					
		.contmax    = 40,  					
		.stability  = 255, 				
		.maxtcharea = 3,            		
		.amplthr    = 30,  					
		.styshape   = 10, 				
		.hoversup   = 80, 					
		.confthr    = 1,   					
		.syncsperx  = 16,  					
		.xposadj    = 0,  					
		.yposadj    = 0,  				
		.cfg        = 0,   
		.reserved[0]  = 0,                    
		.reserved[1]  = 0,                    
		.reserved[2]  = 0,                 
		.reserved[3]  = 0,                    
		.reserved[4]  = 0,                   
		.reserved[5]  = 0,                    
		.reserved[6]  = 0,                    
		.supstyto   = 1,                    
		.maxnumsty  = 0,                    
		.xedgectrl  = 0, 					
		.xedgedist  = 0, 				
		.yedgectrl  = 0, 					
		.yedgedist  = 0,  
		.supto		= 0,
		.supclassmode = 0,
	},
	{	
		.ctrl       = 9,   				
		.contmin    = 15,  					
		.contmax    = 45,  					
		.stability  = 150, 				
		.maxtcharea = 3,            		
		.amplthr    = 30,  					
		.styshape   = 10, 				
		.hoversup   = 250, 					
		.confthr    = 1,   					
		.syncsperx  = 40,  					
		.xposadj    = 0,  					
		.yposadj    = 0,  				
		.cfg        = 3,   
		.reserved[0]  = 0,                    
		.reserved[1]  = 0,                    
		.reserved[2]  = 0,                 
		.reserved[3]  = 0,                    
		.reserved[4]  = 0,                   
		.reserved[5]  = 0,                    
		.reserved[6]  = 0,                    
		.supstyto   = 1,                    
		.maxnumsty  = 0,                    
		.xedgectrl  = 0, 					
		.xedgedist  = 0, 				
		.yedgectrl  = 0, 					
		.yedgedist  = 0,  
		.supto		= 0,
		.supclassmode = 0,
	},
	{	
		.ctrl       = 9,   				
		.contmin    = 15,  					
		.contmax    = 45,  					
		.stability  = 150, 				
		.maxtcharea = 3,            		
		.amplthr    = 30,  					
		.styshape   = 10, 				
		.hoversup   = 250, 					
		.confthr    = 1,   					
		.syncsperx  = 40,  					
		.xposadj    = 0,  					
		.yposadj    = 0,  				
		.cfg        = 3,   
		.reserved[0]  = 0,                    
		.reserved[1]  = 0,                    
		.reserved[2]  = 0,                 
		.reserved[3]  = 0,                    
		.reserved[4]  = 0,                   
		.reserved[5]  = 0,                    
		.reserved[6]  = 0,                    
		.supstyto   = 1,                    
		.maxnumsty  = 0,                    
		.xedgectrl  = 0, 					
		.xedgedist  = 0, 				
		.yedgectrl  = 0, 					
		.yedgedist  = 0,  
		.supto		= 0,
		.supclassmode = 0,
	},
};

static proci_shieldless_t56_config_t obj_slim_sensor_t56[TOUCH_MODE_MAX_NUM] = {
	{
		.ctrl  		 = 1,  							
		.command     = 0,  							    
		.optint		 = 1,  					  
		.inttime     = 60,							    
		.intdelay0	 = 2, 					        
		.intdelay1	 = 2, 						        
		.intdelay2	 = 2, 					        
		.intdelay3	 = 2,  						        
		.intdelay4	 = 2,  					        
		.intdelay5	 = 2, 					        
		.intdelay6	 = 2, 					        
		.intdelay7	 = 2, 					        
		.intdelay8	 = 2,  					        
		.intdelay9	 = 2,  					        
		.intdelay10	 = 2,  					    
		.intdelay11	 = 2, 						
		.intdelay12	 = 2, 					    
		.intdelay13	 = 2,  							
		.intdelay14	 = 2,  					    
		.intdelay15	 = 2,  					    
		.intdelay16	 = 2, 					    
		.intdelay17	 = 2,  						    
		.intdelay18	 = 2,  					    
		.intdelay19	 = 2,  					    
		.intdelay20	 = 2,  						    
		.intdelay21	 = 2,  					      	
		.intdelay22	 = 2,  					    
		.intdelay23	 = 2, 					    
		.intdelay24	 = 2,  					    
		.intdelay25	 = 2,					    
		.intdelay26	 = 2,  						    
		.intdelay27	 = 2,  					    
		.intdelay28	 = 2, 				    
		.intdelay29  = 2,  						    
		.intdelay30  = 2,  						    
		.intdelay31  = 2,  						    
	},
	{
		.ctrl  		 = 1,  							
		.command     = 0,  							    
		.optint		 = 1,  					  
		.inttime     = 60,							    
		.intdelay0	 = 2, 					        
		.intdelay1	 = 2, 						        
		.intdelay2	 = 2, 					        
		.intdelay3	 = 2,  						        
		.intdelay4	 = 2,  					        
		.intdelay5	 = 2, 					        
		.intdelay6	 = 2, 					        
		.intdelay7	 = 2, 					        
		.intdelay8	 = 2,  					        
		.intdelay9	 = 2,  					        
		.intdelay10	 = 2,  					    
		.intdelay11	 = 2, 						
		.intdelay12	 = 2, 					    
		.intdelay13	 = 2,  							
		.intdelay14	 = 2,  					    
		.intdelay15	 = 2,  					    
		.intdelay16	 = 2, 					    
		.intdelay17	 = 2,  						    
		.intdelay18	 = 2,  					    
		.intdelay19	 = 2,  					    
		.intdelay20	 = 2,  						    
		.intdelay21	 = 2,  					      	
		.intdelay22	 = 2,  					    
		.intdelay23	 = 2, 					    
		.intdelay24	 = 2,  					    
		.intdelay25	 = 2,					    
		.intdelay26	 = 2,  						    
		.intdelay27	 = 2,  					    
		.intdelay28	 = 2, 				    
		.intdelay29  = 2,  						    
		.intdelay30  = 2,  						    
		.intdelay31  = 2,  						    
	},
	{
		.ctrl  		 = 1,  							
		.command     = 0,  							    
		.optint		 = 1,  					  
		.inttime     = 60,							    
		.intdelay0	 = 2, 					        
		.intdelay1	 = 2, 						        
		.intdelay2	 = 2, 					        
		.intdelay3	 = 2,  						        
		.intdelay4	 = 2,  					        
		.intdelay5	 = 2, 					        
		.intdelay6	 = 2, 					        
		.intdelay7	 = 2, 					        
		.intdelay8	 = 2,  					        
		.intdelay9	 = 2,  					        
		.intdelay10	 = 2,  					    
		.intdelay11	 = 2, 						
		.intdelay12	 = 2, 					    
		.intdelay13	 = 2,  							
		.intdelay14	 = 2,  					    
		.intdelay15	 = 2,  					    
		.intdelay16	 = 2, 					    
		.intdelay17	 = 2,  						    
		.intdelay18	 = 2,  					    
		.intdelay19	 = 2,  					    
		.intdelay20	 = 2,  						    
		.intdelay21	 = 2,  					      	
		.intdelay22	 = 2,  					    
		.intdelay23	 = 2, 					    
		.intdelay24	 = 2,  					    
		.intdelay25	 = 2,					    
		.intdelay26	 = 2,  						    
		.intdelay27	 = 2,  					    
		.intdelay28	 = 2, 				    
		.intdelay29  = 2,  						    
		.intdelay30  = 2,  						    
		.intdelay31  = 2,  						    
	},
	{
		.ctrl  		 = 1,  							
		.command     = 0,  							    
		.optint		 = 1,  					  
		.inttime     = 60,							    
		.intdelay0	 = 2, 					        
		.intdelay1	 = 2, 						        
		.intdelay2	 = 2, 					        
		.intdelay3	 = 2,  						        
		.intdelay4	 = 2,  					        
		.intdelay5	 = 2, 					        
		.intdelay6	 = 2, 					        
		.intdelay7	 = 2, 					        
		.intdelay8	 = 2,  					        
		.intdelay9	 = 2,  					        
		.intdelay10	 = 2,  					    
		.intdelay11	 = 2, 						
		.intdelay12	 = 2, 					    
		.intdelay13	 = 2,  							
		.intdelay14	 = 2,  					    
		.intdelay15	 = 2,  					    
		.intdelay16	 = 2, 					    
		.intdelay17	 = 2,  						    
		.intdelay18	 = 2,  					    
		.intdelay19	 = 2,  					    
		.intdelay20	 = 2,  						    
		.intdelay21	 = 2,  					      	
		.intdelay22	 = 2,  					    
		.intdelay23	 = 2, 					    
		.intdelay24	 = 2,  					    
		.intdelay25	 = 2,					    
		.intdelay26	 = 2,  						    
		.intdelay27	 = 2,  					    
		.intdelay28	 = 2, 				    
		.intdelay29  = 2,  						    
		.intdelay30  = 2,  						    
		.intdelay31  = 2,  						    
	},
};

static spt_timer_t61_config_t obj_timer_t61[TOUCH_MODE_MAX_NUM] = {
	{
		.ctrl   = 0, 					
		.cmd    = 0, 					
		.mode   = 0, 					
		.period = 0, 			
	},
	{
		.ctrl   = 0, 					
		.cmd    = 0, 					
		.mode   = 0, 					
		.period = 0, 			
	},
	{
		.ctrl   = 0, 					
		.cmd    = 0, 					
		.mode   = 0, 					
		.period = 0, 			
	},
	{
		.ctrl   = 0, 					
		.cmd    = 0, 					
		.mode   = 0, 					
		.period = 0, 			
	},
};

static proci_lensbending_t65_config_t obj_lens_bending_t65[TOUCH_MODE_MAX_NUM] = {
	{
		.ctrl         = 1, 					
		.gradthr      = 6, 				
		.ylonoisemul  = 0, 			
		.ylonoisediv  = 0, 				
		.yhinoisemul  = 0,				
		.yhinoisediv  = 0, 				
		.lpfiltcoef   = 5, 				
		.forcescale   = 0, 									
		.forcethr     = 0,				
		.forcethrhyst = 0, 				
		.forcedi      = 0,					
		.forcehyst    = 0, 
		.atchratio	  = 1,
		.totvarlim    = 0,
		.reserved[0]  = 0,
		.reserved[1]  = 0,
		.reserved[2]  = 0,
	},
	{
		.ctrl         = 1, 					
		.gradthr      = 1, 				
		.ylonoisemul  = 0, 			
		.ylonoisediv  = 0, 				
		.yhinoisemul  = 0,				
		.yhinoisediv  = 0, 				
		.lpfiltcoef   = 1, 				
		.forcescale   = 0, 									
		.forcethr     = 0,				
		.forcethrhyst = 0, 				
		.forcedi      = 0,					
		.forcehyst    = 0, 
		.atchratio	  = 1,
		.totvarlim    = 0,
		.reserved[0]  = 0,
		.reserved[1]  = 0,
		.reserved[2]  = 0,
	},
	{
		.ctrl         = 1, 					
		.gradthr      = 1, 				
		.ylonoisemul  = 0, 			
		.ylonoisediv  = 0, 				
		.yhinoisemul  = 0,				
		.yhinoisediv  = 0, 				
		.lpfiltcoef   = 5, 				
		.forcescale   = 0, 									
		.forcethr     = 0,				
		.forcethrhyst = 0, 				
		.forcedi      = 0,					
		.forcehyst    = 0, 
		.atchratio	  = 1,
		.totvarlim    = 0,
		.reserved[0]  = 0,
		.reserved[1]  = 0,
		.reserved[2]  = 0,
	},
	{
		.ctrl         = 1, 					
		.gradthr      = 1, 				
		.ylonoisemul  = 0, 			
		.ylonoisediv  = 0, 				
		.yhinoisemul  = 0,				
		.yhinoisediv  = 0, 				
		.lpfiltcoef   = 5, 				
		.forcescale   = 0, 									
		.forcethr     = 0,				
		.forcethrhyst = 0, 				
		.forcedi      = 0,					
		.forcehyst    = 0, 
		.atchratio	  = 1,
		.totvarlim    = 0,
		.reserved[0]  = 0,
		.reserved[1]  = 0,
		.reserved[2]  = 0,
	},
};

#define T70_MAX_INSTANCE_SIZE		20
static spt_dynamiccfgcontroller_t70_config_t obj_dynamic_config_controller_t70[TOUCH_MODE_MAX_NUM][T70_MAX_INSTANCE_SIZE] = {
	{
		{
			.ctrl      = 0,			
			.event     = 0,			
			.objtype   = 0,	
			.reserved= 0,			
			.objinst   = 0,		
			.dstoffset = 0,			
			.srcoffset = 0,			
			.length    = 0,		    
		},
		{
			.ctrl      = 0,			
			.event     = 0,			
			.objtype   = 0,	
			.reserved= 0,			
			.objinst   = 0,		
			.dstoffset = 0,			
			.srcoffset = 0,			
			.length    = 0,		    
		},
		{
			.ctrl      = 0,			
			.event     = 0,			
			.objtype   = 0,	
			.reserved= 0,			
			.objinst   = 0,		
			.dstoffset = 0,			
			.srcoffset = 0,			
			.length    = 0,		    
		},
	},
	{
		{
			.ctrl      = 0,			
			.event     = 0,			
			.objtype   = 0,	
			.reserved= 0,			
			.objinst   = 0,		
			.dstoffset = 0,			
			.srcoffset = 0,			
			.length    = 0,		    
		},
		{
			.ctrl      = 0,			
			.event     = 0,			
			.objtype   = 0,	
			.reserved= 0,			
			.objinst   = 0,		
			.dstoffset = 0,			
			.srcoffset = 0,			
			.length    = 0,		    
		},
		{
			.ctrl      = 0,			
			.event     = 0,			
			.objtype   = 0,	
			.reserved= 0,			
			.objinst   = 0,		
			.dstoffset = 0,			
			.srcoffset = 0,			
			.length    = 0,		    
		},
	},
	{
		{
			.ctrl      = 0,			
			.event     = 0,			
			.objtype   = 0,	
			.reserved= 0,			
			.objinst   = 0,		
			.dstoffset = 0,			
			.srcoffset = 0,			
			.length    = 0,		    
		},
		{
			.ctrl      = 0,			
			.event     = 0,			
			.objtype   = 0,	
			.reserved= 0,			
			.objinst   = 0,		
			.dstoffset = 0,			
			.srcoffset = 0,			
			.length    = 0,		    
		},
		{
			.ctrl      = 0,			
			.event     = 0,			
			.objtype   = 0,	
			.reserved= 0,			
			.objinst   = 0,		
			.dstoffset = 0,			
			.srcoffset = 0,			
			.length    = 0,		    
		},
	},
	{
		{
			.ctrl      = 0,			
			.event     = 0,			
			.objtype   = 0,	
			.reserved= 0,			
			.objinst   = 0,		
			.dstoffset = 0,			
			.srcoffset = 0,			
			.length    = 0,		    
		},
		{
			.ctrl      = 0,			
			.event     = 0,			
			.objtype   = 0,	
			.reserved= 0,			
			.objinst   = 0,		
			.dstoffset = 0,			
			.srcoffset = 0,			
			.length    = 0,		    
		},
		{
			.ctrl      = 0,			
			.event     = 0,			
			.objtype   = 0,	
			.reserved= 0,			
			.objinst   = 0,		
			.dstoffset = 0,			
			.srcoffset = 0,			
			.length    = 0,		    
		},
	}
};

/* SPT_DYNAMICCONFIGURATIONCONTAINER_T71 */
static spt_dynamiccfgcontainer_t71_config_t obj_dynamic_config_container_t71[TOUCH_MODE_MAX_NUM] = 
{
	{
		.data[0] =  0,
		.data[1] =  0,		
		.data[2] =  0,		
		.data[3] =  0,		
		.data[4] =  0,		
		.data[5] =  0,	
		.data[6] =  0,	
		.data[7] =  0,		
		.data[8] =  0,		
		.data[9] =  0,		
		.data[10] = 0,		
		.data[11] = 0,	
		.data[12] = 0,		
	},	
	{
		.data[0] =  0,
		.data[1] =  0,		
		.data[2] =  0,		
		.data[3] =  0,		
		.data[4] =  0,		
		.data[5] =  0,	
		.data[6] =  0,	
		.data[7] =  0,		
		.data[8] =  0,		
		.data[9] =  0,		
		.data[10] = 0,		
		.data[11] = 0,	
		.data[12] = 0,		
	},
	{
		.data[0] =  0,
		.data[1] =  0,		
		.data[2] =  0,		
		.data[3] =  0,		
		.data[4] =  0,		
		.data[5] =  0,	
		.data[6] =  0,	
		.data[7] =  0,		
		.data[8] =  0,		
		.data[9] =  0,		
		.data[10] = 0,		
		.data[11] = 0,	
		.data[12] = 0,		
	},
	{
		.data[0] =  0,
		.data[1] =  0,		
		.data[2] =  0,		
		.data[3] =  0,		
		.data[4] =  0,		
		.data[5] =  0,	
		.data[6] =  0,	
		.data[7] =  0,		
		.data[8] =  0,		
		.data[9] =  0,		
		.data[10] = 0,		
		.data[11] = 0,	
		.data[12] = 0,		
	}
};

static procg_noisesuppression_t72_config_t obj_mxt_charger_t72[TOUCH_MODE_MAX_NUM] = {
	{	
		.ctrl           = 253, 		
		.calcfg1        = 0,   		
		.cfg1           = 0,  			
		.cfg2           = 17,  		
		.debugcfg     	= 0,  	
		.hopcnt         = 5,   		
		.hopcntper      = 5,      
		.hopevalto      = 5,     
		.hopst          = 2,   		
		.nlgaindualx    = 8,  
		.minnlthr       = 30,  	
		.incnlthr       = 5,  		
		.fallnlthr      = 5,   		
		.nlthrmargin    = 5,   	
		.minthradj      = 32,  	
		.nlthrlimit     = 100,  
		.bgscan			= 13,      
		.nlgainsingx    = 12,  
		.blknlthr       = 0,   		
		.cfg3 			= 0,   		
		.stabctrl       = 0,   		
		.stabfreq[0]    = 3,  
		.stabfreq[1]    = 9,  
		.stabfreq[2]    = 10, 
		.stabfreq[3]    = 11, 
		.stabfreq[4]    = 12, 
		.stabtchapx[0]  = 32,  
		.stabtchapx[1]  = 32, 
		.stabtchapx[2]  = 32,  
		.stabtchapx[3]  = 32, 
		.stabtchapx[4]  = 32,  
		.stabnotchapx[0]= 32, 
		.stabnotchapx[1]= 32, 
		.stabnotchapx[2]= 32,  
		.stabnotchapx[3]= 32, 
		.stabnotchapx[4]= 32,  
		.stabpc		    = 0,   		
		.reserved	    = 0,   	
		.stabhighnlthr  = 10,   	
		.stabcnt	    = 0,  
		.noisctrl       = 15, 		
		.noisfreq[0]    = 11,  	
		.noisfreq[1]    = 12,  
		.noisfreq[2]    = 13, 
		.noisfreq[3]    = 14,  
		.noisfreq[4]    = 21,
		.noistchapx[0]  = 52,  
		.noistchapx[1]  = 52,  
		.noistchapx[2]  = 52,  
		.noistchapx[3]  = 52,  
		.noistchapx[4]  = 52,  
		.noisnotchapx[0]= 52, 
		.noisnotchapx[1]= 52, 
		.noisnotchapx[2]= 52,  
		.noisnotchapx[3]= 52,  
		.noisnotchapx[4]= 52, 
		.noispc	    	= 0,  
		.noislownlthr   = 8,   
		.noishighnlthr  = 15,  
		.noiscnt        = 51,   		
		.vnoictrl       = 15,  		
		.vnoifreq[0]    = 30, 
		.vnoifreq[1]    = 30, 
		.vnoifreq[2]    = 30,
		.vnoifreq[3]    = 30,  	
		.vnoifreq[4]    = 30, 
		.vnoitchapx[0]  = 60,  
		.vnoitchapx[1]  = 60,  
		.vnoitchapx[2]  = 60,  	
		.vnoitchapx[3]  = 60,  
		.vnoitchapx[4]  = 60,  	
		.vnoinotchapx[0]= 60, 
		.vnoinotchapx[1]= 60,  
		.vnoinotchapx[2]= 60,  
		.vnoinotchapx[3]= 60, 
		.vnoinotchapx[4]= 60,  
		.vnoipc     	= 0,  	
		.vnoilownlthr   = 14,  
		.reserved_1     = 0,   		
		.vnoicnt        = 119, 
		.reserved_2  	= 0,
		.notchmindiff  	= 0,
		.tchmindiff  	= 0,
		.notchminhop  	= 0,
		.tchminhop  	= 0,
	},
	{	
		.ctrl           = 253, 		
		.calcfg1        = 0,   		
		.cfg1           = 0,  			
		.cfg2           = 17,  		
		.debugcfg     	= 0,  	
		.hopcnt         = 5,   		
		.hopcntper      = 5,      
		.hopevalto      = 5,     
		.hopst          = 2,   		
		.nlgaindualx    = 8,  
		.minnlthr       = 25,  	
		.incnlthr       = 25,  		
		.fallnlthr      = 5,   		
		.nlthrmargin    = 5,   	
		.minthradj      = 16,  	
		.nlthrlimit     = 40,  
		.bgscan			= 13,      
		.nlgainsingx    = 12,  
		.blknlthr       = 0,   		
		.cfg3 			= 0,   		
		.stabctrl       = 0,   		
		.stabfreq[0]    = 3,  
		.stabfreq[1]    = 9,  
		.stabfreq[2]    = 10, 
		.stabfreq[3]    = 11, 
		.stabfreq[4]    = 12, 
		.stabtchapx[0]  = 32,  
		.stabtchapx[1]  = 32, 
		.stabtchapx[2]  = 32,  
		.stabtchapx[3]  = 32, 
		.stabtchapx[4]  = 32,  
		.stabnotchapx[0]= 32, 
		.stabnotchapx[1]= 32, 
		.stabnotchapx[2]= 32,  
		.stabnotchapx[3]= 32, 
		.stabnotchapx[4]= 32,  
		.stabpc		    = 0,   		
		.reserved	    = 0,   	
		.stabhighnlthr  = 10,   	
		.stabcnt	    = 0,  
		.noisctrl       = 15, 		
		.noisfreq[0]    = 11,  	
		.noisfreq[1]    = 12,  
		.noisfreq[2]    = 13, 
		.noisfreq[3]    = 14,  
		.noisfreq[4]    = 21,
		.noistchapx[0]  = 52,  
		.noistchapx[1]  = 52,  
		.noistchapx[2]  = 52,  
		.noistchapx[3]  = 52,  
		.noistchapx[4]  = 52,  
		.noisnotchapx[0]= 52, 
		.noisnotchapx[1]= 52, 
		.noisnotchapx[2]= 52,  
		.noisnotchapx[3]= 52,  
		.noisnotchapx[4]= 52, 
		.noispc	    	= 0,  
		.noislownlthr   = 8,   
		.noishighnlthr  = 15,  
		.noiscnt        = 51,   		
		.vnoictrl       = 15,  		
		.vnoifreq[0]    = 30, 
		.vnoifreq[1]    = 30, 
		.vnoifreq[2]    = 30,
		.vnoifreq[3]    = 30,  	
		.vnoifreq[4]    = 30, 
		.vnoitchapx[0]  = 60,  
		.vnoitchapx[1]  = 60,  
		.vnoitchapx[2]  = 60,  	
		.vnoitchapx[3]  = 60,  
		.vnoitchapx[4]  = 60,  	
		.vnoinotchapx[0]= 60, 
		.vnoinotchapx[1]= 60,  
		.vnoinotchapx[2]= 60,  
		.vnoinotchapx[3]= 60, 
		.vnoinotchapx[4]= 60,  
		.vnoipc     	= 0,  	
		.vnoilownlthr   = 14,  
		.reserved_1     = 0,   		
		.vnoicnt        = 119, 
		.reserved_2  	= 0,
		.notchmindiff  	= 0,
		.tchmindiff  	= 0,
		.notchminhop  	= 0,
		.tchminhop  	= 0,
	},
	{	
		.ctrl           = 253, 		
		.calcfg1        = 0,   		
		.cfg1           = 0,  			
		.cfg2           = 17,  		
		.debugcfg     	= 0,  	
		.hopcnt         = 5,   		
		.hopcntper      = 5,      
		.hopevalto      = 5,     
		.hopst          = 2,   		
		.nlgaindualx    = 8,  
		.minnlthr       = 30,  	
		.incnlthr       = 5,  		
		.fallnlthr      = 5,   		
		.nlthrmargin    = 5,   	
		.minthradj      = 32,  	
		.nlthrlimit     = 100,  
		.bgscan			= 13,      
		.nlgainsingx    = 12,  
		.blknlthr       = 0,   		
		.cfg3 			= 0,   		
		.stabctrl       = 0,   		
		.stabfreq[0]    = 3,  
		.stabfreq[1]    = 9,  
		.stabfreq[2]    = 10, 
		.stabfreq[3]    = 11, 
		.stabfreq[4]    = 12, 
		.stabtchapx[0]  = 32,  
		.stabtchapx[1]  = 32, 
		.stabtchapx[2]  = 32,  
		.stabtchapx[3]  = 32, 
		.stabtchapx[4]  = 32,  
		.stabnotchapx[0]= 32, 
		.stabnotchapx[1]= 32, 
		.stabnotchapx[2]= 32,  
		.stabnotchapx[3]= 32, 
		.stabnotchapx[4]= 32,  
		.stabpc		    = 0,   		
		.reserved	    = 0,   	
		.stabhighnlthr  = 10,   	
		.stabcnt	    = 0,  
		.noisctrl       = 15, 		
		.noisfreq[0]    = 11,  	
		.noisfreq[1]    = 12,  
		.noisfreq[2]    = 13, 
		.noisfreq[3]    = 14,  
		.noisfreq[4]    = 21,
		.noistchapx[0]  = 52,  
		.noistchapx[1]  = 52,  
		.noistchapx[2]  = 52,  
		.noistchapx[3]  = 52,  
		.noistchapx[4]  = 52,  
		.noisnotchapx[0]= 52, 
		.noisnotchapx[1]= 52, 
		.noisnotchapx[2]= 52,  
		.noisnotchapx[3]= 52,  
		.noisnotchapx[4]= 52, 
		.noispc	    	= 0,  
		.noislownlthr   = 8,   
		.noishighnlthr  = 15,  
		.noiscnt        = 51,   		
		.vnoictrl       = 15,  		
		.vnoifreq[0]    = 30, 
		.vnoifreq[1]    = 30, 
		.vnoifreq[2]    = 30,
		.vnoifreq[3]    = 30,  	
		.vnoifreq[4]    = 30, 
		.vnoitchapx[0]  = 60,  
		.vnoitchapx[1]  = 60,  
		.vnoitchapx[2]  = 60,  	
		.vnoitchapx[3]  = 60,  
		.vnoitchapx[4]  = 60,  	
		.vnoinotchapx[0]= 60, 
		.vnoinotchapx[1]= 60,  
		.vnoinotchapx[2]= 60,  
		.vnoinotchapx[3]= 60, 
		.vnoinotchapx[4]= 60,  
		.vnoipc     	= 0,  	
		.vnoilownlthr   = 14,  
		.reserved_1     = 0,   		
		.vnoicnt        = 119, 
		.reserved_2  	= 0,
		.notchmindiff  	= 0,
		.tchmindiff  	= 0,
		.notchminhop  	= 0,
		.tchminhop  	= 0,
	},
	{	
		.ctrl           = 253, 		
		.calcfg1        = 0,   		
		.cfg1           = 0,  			
		.cfg2           = 17,  		
		.debugcfg     	= 0,  	
		.hopcnt         = 5,   		
		.hopcntper      = 5,      
		.hopevalto      = 5,     
		.hopst          = 2,   		
		.nlgaindualx    = 8,  
		.minnlthr       = 30,  	
		.incnlthr       = 5,  		
		.fallnlthr      = 5,   		
		.nlthrmargin    = 5,   	
		.minthradj      = 32,  	
		.nlthrlimit     = 100,  
		.bgscan			= 13,      
		.nlgainsingx    = 12,  
		.blknlthr       = 0,   		
		.cfg3 			= 0,   		
		.stabctrl       = 0,   		
		.stabfreq[0]    = 3,  
		.stabfreq[1]    = 9,  
		.stabfreq[2]    = 10, 
		.stabfreq[3]    = 11, 
		.stabfreq[4]    = 12, 
		.stabtchapx[0]  = 32,  
		.stabtchapx[1]  = 32, 
		.stabtchapx[2]  = 32,  
		.stabtchapx[3]  = 32, 
		.stabtchapx[4]  = 32,  
		.stabnotchapx[0]= 32, 
		.stabnotchapx[1]= 32, 
		.stabnotchapx[2]= 32,  
		.stabnotchapx[3]= 32, 
		.stabnotchapx[4]= 32,  
		.stabpc		    = 0,   		
		.reserved	    = 0,   	
		.stabhighnlthr  = 10,   	
		.stabcnt	    = 0,  
		.noisctrl       = 15, 		
		.noisfreq[0]    = 11,  	
		.noisfreq[1]    = 12,  
		.noisfreq[2]    = 13, 
		.noisfreq[3]    = 14,  
		.noisfreq[4]    = 21,
		.noistchapx[0]  = 52,  
		.noistchapx[1]  = 52,  
		.noistchapx[2]  = 52,  
		.noistchapx[3]  = 52,  
		.noistchapx[4]  = 52,  
		.noisnotchapx[0]= 52, 
		.noisnotchapx[1]= 52, 
		.noisnotchapx[2]= 52,  
		.noisnotchapx[3]= 52,  
		.noisnotchapx[4]= 52, 
		.noispc	    	= 0,  
		.noislownlthr   = 8,   
		.noishighnlthr  = 15,  
		.noiscnt        = 51,   		
		.vnoictrl       = 15,  		
		.vnoifreq[0]    = 30, 
		.vnoifreq[1]    = 30, 
		.vnoifreq[2]    = 30,
		.vnoifreq[3]    = 30,  	
		.vnoifreq[4]    = 30, 
		.vnoitchapx[0]  = 60,  
		.vnoitchapx[1]  = 60,  
		.vnoitchapx[2]  = 60,  	
		.vnoitchapx[3]  = 60,  
		.vnoitchapx[4]  = 60,  	
		.vnoinotchapx[0]= 60, 
		.vnoinotchapx[1]= 60,  
		.vnoinotchapx[2]= 60,  
		.vnoinotchapx[3]= 60, 
		.vnoinotchapx[4]= 60,  
		.vnoipc     	= 0,  	
		.vnoilownlthr   = 14,  
		.reserved_1     = 0,   		
		.vnoicnt        = 119, 
		.reserved_2  	= 0,
		.notchmindiff  	= 0,
		.tchmindiff  	= 0,
		.notchminhop  	= 0,
		.tchminhop  	= 0,
	},
};

static proci_glovedetection_t78_config_t obj_glove_detect_t78[TOUCH_MODE_MAX_NUM] = {
	{
		.ctrl         = 0, 
		.minarea	  = 4,	 
		.confthr	  = 10,	
		.mindist	  = 15,	
		.glovemodeto  = 0,	 
		.supto		  = 2,	 
		.syncsperx	  = 16,	
		.hithrmrgn	  = 0,
		.reserved[0]  = 0,
		.reserved[1]  = 0,
		.reserved[2]  = 0,
		.reserved[3]  = 0,
	},
	{
		.ctrl         = 1, 
		.minarea	  = 3,	 
		.confthr	  = 5,	
		.mindist	  = 0,	
		.glovemodeto  = 3,	 
		.supto		  = 3,	 
		.syncsperx	  = 32,	
		.hithrmrgn	  = 5,
		.reserved[0]  = 0,
		.reserved[1]  = 0,
		.reserved[2]  = 0,
		.reserved[3]  = 0,
	},
	{
		.ctrl         = 0, 
		.minarea	  = 4,	 
		.confthr	  = 10,	
		.mindist	  = 15,	
		.glovemodeto  = 0,	 
		.supto		  = 2,	 
		.syncsperx	  = 16,	
		.hithrmrgn	  = 0,
		.reserved[0]  = 0,
		.reserved[1]  = 0,
		.reserved[2]  = 0,
		.reserved[3]  = 0,
	},
	{
		.ctrl         = 0, 
		.minarea	  = 4,	 
		.confthr	  = 10,	
		.mindist	  = 15,	
		.glovemodeto  = 0,	 
		.supto		  = 2,	 
		.syncsperx	  = 16,	
		.hithrmrgn	  = 0,
		.reserved[0]  = 0,
		.reserved[1]  = 0,
		.reserved[2]  = 0,
		.reserved[3]  = 0,
	},
};

static proci_retransmissioncompensation_t80_config_t obj_retransmissioncompensation_t80[TOUCH_MODE_MAX_NUM] = {
	{
		.ctrl         = 25,  
		.compgain	  = 30,	 
		.targetdelta  = 120,	
		.compthr	  = 10,	
		.atchthr      = 10,	
		.moistcfg     = 212,	
		.moistdto     = 5,	
		.reserved	  = 0,
		.reserved_1   = 0,
	},
	{
		.ctrl         = 25,  
		.compgain	  = 30,	 
		.targetdelta  = 120,	
		.compthr	  = 10,	
		.atchthr      = 10,	
		.moistcfg     = 212,	
		.moistdto     = 5,	
		.reserved	  = 0,
		.reserved_1   = 0,
	},
	{
		.ctrl         = 25,  
		.compgain	  = 30,	 
		.targetdelta  = 120,	
		.compthr	  = 10,	
		.atchthr      = 10,	
		.moistcfg     = 212,	
		.moistdto     = 5,	
		.reserved	  = 0,
		.reserved_1   = 0,
	},
	{
		.ctrl         = 25,  
		.compgain	  = 30,	 
		.targetdelta  = 120,	
		.compthr	  = 10,	
		.atchthr      = 10,	
		.moistcfg     = 212,	
		.moistdto     = 5,	
		.reserved	  = 0,
		.reserved_1   = 0,
	},
};

static proci_gesturepocessor_t84_config_t obj_gesturepocessor_t84[TOUCH_MODE_MAX_NUM] = {
	{
		.ctrl		= 0,
		.zonethr	= 0,  
		.direl		= 0,
		.dto		= 0,
	},
	{
	    .ctrl		= 0,
		.zonethr	= 0,  
		.direl		= 0,
		.dto		= 0,
	},
	{
		.ctrl		= 0,
		.zonethr	= 0,  
		.direl		= 0,
		.dto		= 0,
	},
	{
		.ctrl		= 0,
		.zonethr	= 0,  
		.direl		= 0,
		.dto		= 0,
	},
};

static touch_multitouchscreen_t100_config_t obj_multi_touch_t100[TOUCH_MODE_MAX_NUM] = {
	{	
		.ctrl         = 143,   
		.cfg1         = 48,  
		.scraux       = 0,	  
		.tchaux       = 0,	  
		.tcheventcfg  = 0,	  
		.akscfg       = 0,	  
		.numtch       = 10,	   
		.xycfg        = 0,   
		.xorigin      = 0,	   
		.xsize        = 32,	  
		.xpitch       = 0,	  
		.xloclip      = 0,	   
		.xhiclip      = 0,	  
		.xrange       = (SCREEN_RESOLUTION_WHOLE_Y-1),  
		.xedgecfg     = 0,	  
		.xedgedist    = 0,	   
		.dxxedgecfg   = 0,	  
		.dxxedgedist  = 0,	   
		.yorigin      = 0,	   
		.ysize        = 17,	   
		.ypitch       = 0,	  
		.yloclip      = 0,	  
		.yhiclip      = 0,	  
		.yrange       = (SCREEN_RESOLUTION_X-1),  
		.yedgecfg     = 0,	  
		.yedgedist    = 0,	   
		.gain         = 12,	  
		.dxgain       = 8,	  
		.tchthr       = 100,	 
		.tchhyst      = 25,	 
		.intthr       = 40,	  
		.noisesf      = 0,	 
		.cutoffthr    = 0,	
		.mrgthr       = 100,	 
		.mrgthradjstr = 0,	 
		.mrghyst      = 10,	  
		.dxthrsf      = 0,	
		.tchdidown    = 2,	 
		.tchdiup      = 2,	  
		.nexttchdi    = 1,	
		.reserved     = 0,	 
		.jumplimit    = 10,	
		.movfilter    = 66,	
		.movsmooth    = 170,
		.movpred      = 48,	  
		.movhysti     = 30,	 
		.movhystn     = 20,	  
		.amplhyst     = 0,	 
		.scrareahyst  = 0,	  
		.intthrhyst   = 10,  
	},
	{	
		.ctrl         = 143,   
		.cfg1         = 48,  
		.scraux       = 0,	  
		.tchaux       = 0,	  
		.tcheventcfg  = 0,	  
		.akscfg       = 0,	  
		.numtch       = 10,	   
		.xycfg        = 0,   
		.xorigin      = 0,	   
		.xsize        = 32,	  
		.xpitch       = 0,	  
		.xloclip      = 0,	   
		.xhiclip      = 0,	  
		.xrange       = (SCREEN_RESOLUTION_WHOLE_Y-1),  
		.xedgecfg     = 0,	  
		.xedgedist    = 0,	   
		.dxxedgecfg   = 0,	  
		.dxxedgedist  = 0,	   
		.yorigin      = 0,	   
		.ysize        = 17,	   
		.ypitch       = 0,	  
		.yloclip      = 0,	  
		.yhiclip      = 0,	  
		.yrange       = (SCREEN_RESOLUTION_X-1),  
		.yedgecfg     = 0,	  
		.yedgedist    = 0,	   
		.gain         = 12,	  
		.dxgain       = 8,	  
		.tchthr       = 50,	 
		.tchhyst      = 12,	 
		.intthr       = 15,	  
		.noisesf      = 0,	 
		.cutoffthr    = 0,	
		.mrgthr       = 80,	 
		.mrgthradjstr = 0,	 
		.mrghyst      = 10,	  
		.dxthrsf      = 0,	
		.tchdidown    = 2,	 
		.tchdiup      = 2,	  
		.nexttchdi    = 1,	
		.reserved     = 0,	 
		.jumplimit    = 10,	
		.movfilter    = 66,	
		.movsmooth    = 170,
		.movpred      = 48,	  
		.movhysti     = 30,	 
		.movhystn     = 20,	  
		.amplhyst     = 0,	 
		.scrareahyst  = 0,	  
		.intthrhyst   = 4,  
	},
	{	
		.ctrl         = 143,   
		.cfg1         = 48,  
		.scraux       = 0,	  
		.tchaux       = 0,	  
		.tcheventcfg  = 0,	  
		.akscfg       = 0,	  
		.numtch       = 10,	   
		.xycfg        = 0,   
		.xorigin      = 0,	   
		.xsize        = 32,	  
		.xpitch       = 42,	  
		.xloclip      = 0,	   
		.xhiclip      = 0,	  
		.xrange       = (SCREEN_RESOLUTION_WHOLE_Y-1),  
		.xedgecfg     = 0,	  
		.xedgedist    = 0,	   
		.dxxedgecfg   = 0,	  
		.dxxedgedist  = 0,	   
		.yorigin      = 0,	   
		.ysize        = 17,	   
		.ypitch       = 42,	  
		.yloclip      = 0,	  
		.yhiclip      = 0,	  
		.yrange       = (SCREEN_RESOLUTION_X-1),  
		.yedgecfg     = 0,	  
		.yedgedist    = 0,	   
		.gain         = 12,	  
		.dxgain       = 8,	  
		.tchthr       = 100,	 
		.tchhyst      = 25,	 
		.intthr       = 20,	  
		.noisesf      = 0,	 
		.cutoffthr    = 0,	
		.mrgthr       = 150,	 
		.mrgthradjstr = 0,	 
		.mrghyst      = 40,	  
		.dxthrsf      = 0,	
		.tchdidown    = 1,	 
		.tchdiup      = 1,	  
		.nexttchdi    = 1,	
		.reserved     = 0,	 
		.jumplimit    = 10,	
		.movfilter    = 4,	
		.movsmooth    = 160,
		.movpred      = 48,	  
		.movhysti     = 2,	 
		.movhystn     = 1,	  
		.amplhyst     = 0,	 
		.scrareahyst  = 0,	  
		.intthrhyst   = 5,  
	},
	{	
		.ctrl         = 143,   
		.cfg1         = 48,  
		.scraux       = 0,	  
		.tchaux       = 0,	  
		.tcheventcfg  = 0,	  
		.akscfg       = 0,	  
		.numtch       = 10,	   
		.xycfg        = 0,   
		.xorigin      = 0,	   
		.xsize        = 32,	  
		.xpitch       = 42,	  
		.xloclip      = 0,	   
		.xhiclip      = 0,	  
		.xrange       = (SCREEN_RESOLUTION_WHOLE_Y-1),  
		.xedgecfg     = 0,	  
		.xedgedist    = 0,	   
		.dxxedgecfg   = 0,	  
		.dxxedgedist  = 0,	   
		.yorigin      = 0,	   
		.ysize        = 17,	   
		.ypitch       = 42,	  
		.yloclip      = 0,	  
		.yhiclip      = 0,	  
		.yrange       = (SCREEN_RESOLUTION_X-1),  
		.yedgecfg     = 0,	  
		.yedgedist    = 0,	   
		.gain         = 12,	  
		.dxgain       = 8,	  
		.tchthr       = 100,	 
		.tchhyst      = 25,	 
		.intthr       = 20,	  
		.noisesf      = 0,	 
		.cutoffthr    = 0,	
		.mrgthr       = 150,	 
		.mrgthradjstr = 0,	 
		.mrghyst      = 40,	  
		.dxthrsf      = 0,	
		.tchdidown    = 1,	 
		.tchdiup      = 1,	  
		.nexttchdi    = 1,	
		.reserved     = 0,	 
		.jumplimit    = 10,	
		.movfilter    = 4,	
		.movsmooth    = 160,
		.movpred      = 48,	  
		.movhysti     = 2,	 
		.movhystn     = 1,	  
		.amplhyst     = 0,	 
		.scrareahyst  = 0,	  
		.intthrhyst   = 5,  
	},
};

static spt_touchscreenhover_t101_config_t obj_touchscreenhover_t101[TOUCH_MODE_MAX_NUM] = {
	{
		.ctrl			= 0,
		.xloclip		= 0,	
		.xhiclip		= 0,
		.xedgecfg		= 0,
		.xedgedist		= 0,
		.xgain			= 0,
		.xhvrthr		= 0,
		.xhvrhyst		= 0,
		.yloclip		= 0,
		.yhiclip		= 0,
		.yedgecfg		= 0,
		.yedgedist		= 0,
		.ygain			= 0,
		.yhvthr			= 0,	
		.yhvrhyst		= 0,
		.hvrdi			= 0,
		.confthr		= 0,
		.movfilter		= 0,
		.movsmooth		= 0,
		.movpred		= 0,
		.movhysti		= 0,
		.movhystn		= 0,
		.hvraux			= 0,
		.reserved		= 0,
	},
	{
		.ctrl			= 0,
		.xloclip		= 0,	
		.xhiclip		= 0,
		.xedgecfg		= 0,
		.xedgedist		= 0,
		.xgain			= 0,
		.xhvrthr		= 0,
		.xhvrhyst		= 0,
		.yloclip		= 0,
		.yhiclip		= 0,
		.yedgecfg		= 0,
		.yedgedist		= 0,
		.ygain			= 0,
		.yhvthr			= 0,	
		.yhvrhyst		= 0,
		.hvrdi			= 0,
		.confthr		= 0,
		.movfilter		= 0,
		.movsmooth		= 0,
		.movpred		= 0,
		.movhysti		= 0,
		.movhystn		= 0,
		.hvraux			= 0,
		.reserved		= 0,
	},
	{
		.ctrl			= 0,
		.xloclip		= 0,	
		.xhiclip		= 0,
		.xedgecfg		= 0,
		.xedgedist		= 0,
		.xgain			= 0,
		.xhvrthr		= 0,
		.xhvrhyst		= 0,
		.yloclip		= 0,
		.yhiclip		= 0,
		.yedgecfg		= 0,
		.yedgedist		= 0,
		.ygain			= 0,
		.yhvthr			= 0,	
		.yhvrhyst		= 0,
		.hvrdi			= 0,
		.confthr		= 0,
		.movfilter		= 0,
		.movsmooth		= 0,
		.movpred		= 0,
		.movhysti		= 0,
		.movhystn		= 0,
		.hvraux			= 0,
		.reserved		= 0,
	},
	{
		.ctrl			= 0,
		.xloclip		= 0,	
		.xhiclip		= 0,
		.xedgecfg		= 0,
		.xedgedist		= 0,
		.xgain			= 0,
		.xhvrthr		= 0,
		.xhvrhyst		= 0,
		.yloclip		= 0,
		.yhiclip		= 0,
		.yedgecfg		= 0,
		.yedgedist		= 0,
		.ygain			= 0,
		.yhvthr			= 0,	
		.yhvrhyst		= 0,
		.hvrdi			= 0,
		.confthr		= 0,
		.movfilter		= 0,
		.movsmooth		= 0,
		.movpred		= 0,
		.movhysti		= 0,
		.movhystn		= 0,
		.hvraux			= 0,
		.reserved		= 0,
	},
};

static spt_auxtouchconfig_t104_config_t obj_auxtouchconfig_t104[TOUCH_MODE_MAX_NUM] = {
	{
		.ctrl			= 1, 
		.xgain			= 16,	
		.xtchthr		= 25,	
		.xtchhyst		= 6,	
		.xintthr		= 10,
		.xinthyst		= 3,
		.ygain			= 11,	
		.ytchthr		= 25,	
		.ytchhyst		= 6,	
		.yintthr		= 10,	
		.yinthyst		= 3,	
	},
	{
		.ctrl			= 1, 
		.xgain			= 16,	
		.xtchthr		= 20,	
		.xtchhyst		= 5,	
		.xintthr		= 8,
		.xinthyst		= 2,
		.ygain			= 11,	
		.ytchthr		= 20,	
		.ytchhyst		= 5,	
		.yintthr		= 8,	
		.yinthyst		= 2,	
	},
	{
		.ctrl			= 1, 
		.xgain			= 16,	
		.xtchthr		= 25,	
		.xtchhyst		= 6,	
		.xintthr		= 10,
		.xinthyst		= 3,
		.ygain			= 11,	
		.ytchthr		= 25,	
		.ytchhyst		= 6,	
		.yintthr		= 10,	
		.yinthyst		= 3,	
	},
	{
		.ctrl			= 1, 
		.xgain			= 16,	
		.xtchthr		= 25,	
		.xtchhyst		= 6,	
		.xintthr		= 10,
		.xinthyst		= 3,
		.ygain			= 11,	
		.ytchthr		= 25,	
		.ytchhyst		= 6,	
		.yintthr		= 10,	
		.yinthyst		= 3,	
	},
};

static proci_noisesupselfcap_t108_config_t obj_noisesupselfcap_t108[TOUCH_MODE_MAX_NUM] = {
	{
		.ctrl			= 0,
		.calcfg1		= 0,	
		.cfg1			= 0,
		.cfg2			= 0,
		.cfg3			= 0,
		.nlgain			= 0,
		.iircoeff		= 0,	
		.minnltddiff	= 0,
		.minnltdhop		= 0,
		.reserved		= 0,
		.reserved_1		= 0,
		.hopst			= 0,
		.stabctrl		= 0,
		.stabfreq[0]	= 0,
		.stabfreq[1]	= 0,
		.stabfreq[2]	= 0,
		.stabfreq[3]	= 0,
		.stabfreq[4]	= 0,
		.stabtchapx[0]	= 0,
		.stabtchapx[1]	= 0,
		.stabtchapx[2]	= 0,
		.stabtchapx[3]	= 0,
		.stabtchapx[4]	= 0,
		.stabnotchapx[0]= 0,
		.stabnotchapx[1]= 0,
		.stabnotchapx[2]= 0,
		.stabnotchapx[3]= 0,
		.stabnotchapx[4]= 0,
		.reserved_2		= 0,
		.reserved_3		= 0,
		.stabhinltdthr	= 0,
		.reserved_4		= 0,
		.noisctrl       = 0, 		
		.noisfreq[0]    = 0,  	
		.noisfreq[1]    = 0,  	
		.noisfreq[2]    = 0,  	
		.noisfreq[3]    = 0,  	
		.noisfreq[4]    = 0,  	
		.noistchapx[0]  = 0,  
		.noistchapx[1]  = 0,  
		.noistchapx[2]  = 0,  
		.noistchapx[3]  = 0,  
		.noistchapx[4]  = 0,  
		.noisnotchapx[0]= 0, 
		.noisnotchapx[1]= 0, 
		.noisnotchapx[2]= 0, 
		.noisnotchapx[3]= 0, 
		.noisnotchapx[4]= 0, 
		.reserved_5		= 0,
		.noislonltdthr  = 0,   
		.noishinltdthr  = 0,  
		.noiscnt        = 0,   		
		.vnoictrl       = 0,  		
		.vnoifreq[0]    = 0, 
		.vnoifreq[1]    = 0, 
		.vnoifreq[2]    = 0, 
		.vnoifreq[3]    = 0, 
		.vnoifreq[4]    = 0, 
		.vnoitchapx[0]  = 0,  
		.vnoitchapx[1]  = 0,  
		.vnoitchapx[2]  = 0,  
		.vnoitchapx[3]  = 0,  
		.vnoitchapx[4]  = 0,  
		.vnoinotchapx[0]= 0, 
		.vnoinotchapx[1]= 0, 
		.vnoinotchapx[2]= 0, 
		.vnoinotchapx[3]= 0, 
		.vnoinotchapx[4]= 0, 
		.reserved_6     = 0,   	
		.vnoilonltdthr  = 0,  
		.reserved_7     = 0,   		
		.vnoicnt        = 0, 
		.blknltdthr  	= 0,
		.reserved_8  	= 0,
	},
	{
		.ctrl			= 0,
		.calcfg1		= 0,	
		.cfg1			= 0,
		.cfg2			= 0,
		.cfg3			= 0,
		.nlgain			= 0,
		.iircoeff		= 0,	
		.minnltddiff	= 0,
		.minnltdhop		= 0,
		.reserved		= 0,
		.reserved_1		= 0,
		.hopst			= 0,
		.stabctrl		= 0,
		.stabfreq[0]	= 0,
		.stabfreq[1]	= 0,
		.stabfreq[2]	= 0,
		.stabfreq[3]	= 0,
		.stabfreq[4]	= 0,
		.stabtchapx[0]	= 0,
		.stabtchapx[1]	= 0,
		.stabtchapx[2]	= 0,
		.stabtchapx[3]	= 0,
		.stabtchapx[4]	= 0,
		.stabnotchapx[0]= 0,
		.stabnotchapx[1]= 0,
		.stabnotchapx[2]= 0,
		.stabnotchapx[3]= 0,
		.stabnotchapx[4]= 0,
		.reserved_2		= 0,
		.reserved_3		= 0,
		.stabhinltdthr	= 0,
		.reserved_4		= 0,
		.noisctrl       = 0, 		
		.noisfreq[0]    = 0,  	
		.noisfreq[1]    = 0,  	
		.noisfreq[2]    = 0,  	
		.noisfreq[3]    = 0,  	
		.noisfreq[4]    = 0,  	
		.noistchapx[0]  = 0,  
		.noistchapx[1]  = 0,  
		.noistchapx[2]  = 0,  
		.noistchapx[3]  = 0,  
		.noistchapx[4]  = 0,  
		.noisnotchapx[0]= 0, 
		.noisnotchapx[1]= 0, 
		.noisnotchapx[2]= 0, 
		.noisnotchapx[3]= 0, 
		.noisnotchapx[4]= 0, 
		.reserved_5		= 0,
		.noislonltdthr  = 0,   
		.noishinltdthr  = 0,  
		.noiscnt        = 0,   		
		.vnoictrl       = 0,  		
		.vnoifreq[0]    = 0, 
		.vnoifreq[1]    = 0, 
		.vnoifreq[2]    = 0, 
		.vnoifreq[3]    = 0, 
		.vnoifreq[4]    = 0, 
		.vnoitchapx[0]  = 0,  
		.vnoitchapx[1]  = 0,  
		.vnoitchapx[2]  = 0,  
		.vnoitchapx[3]  = 0,  
		.vnoitchapx[4]  = 0,  
		.vnoinotchapx[0]= 0, 
		.vnoinotchapx[1]= 0, 
		.vnoinotchapx[2]= 0, 
		.vnoinotchapx[3]= 0, 
		.vnoinotchapx[4]= 0, 
		.reserved_6     = 0,   	
		.vnoilonltdthr  = 0,  
		.reserved_7     = 0,   		
		.vnoicnt        = 0, 
		.blknltdthr  	= 0,
		.reserved_8  	= 0,
	},
	{
		.ctrl			= 0,
		.calcfg1		= 0,	
		.cfg1			= 0,
		.cfg2			= 0,
		.cfg3			= 0,
		.nlgain			= 0,
		.iircoeff		= 0,	
		.minnltddiff	= 0,
		.minnltdhop		= 0,
		.reserved		= 0,
		.reserved_1		= 0,
		.hopst			= 0,
		.stabctrl		= 0,
		.stabfreq[0]	= 0,
		.stabfreq[1]	= 0,
		.stabfreq[2]	= 0,
		.stabfreq[3]	= 0,
		.stabfreq[4]	= 0,
		.stabtchapx[0]	= 0,
		.stabtchapx[1]	= 0,
		.stabtchapx[2]	= 0,
		.stabtchapx[3]	= 0,
		.stabtchapx[4]	= 0,
		.stabnotchapx[0]= 0,
		.stabnotchapx[1]= 0,
		.stabnotchapx[2]= 0,
		.stabnotchapx[3]= 0,
		.stabnotchapx[4]= 0,
		.reserved_2		= 0,
		.reserved_3		= 0,
		.stabhinltdthr	= 0,
		.reserved_4		= 0,
		.noisctrl       = 0, 		
		.noisfreq[0]    = 0,  	
		.noisfreq[1]    = 0,  	
		.noisfreq[2]    = 0,  	
		.noisfreq[3]    = 0,  	
		.noisfreq[4]    = 0,  	
		.noistchapx[0]  = 0,  
		.noistchapx[1]  = 0,  
		.noistchapx[2]  = 0,  
		.noistchapx[3]  = 0,  
		.noistchapx[4]  = 0,  
		.noisnotchapx[0]= 0, 
		.noisnotchapx[1]= 0, 
		.noisnotchapx[2]= 0, 
		.noisnotchapx[3]= 0, 
		.noisnotchapx[4]= 0, 
		.reserved_5		= 0,
		.noislonltdthr  = 0,   
		.noishinltdthr  = 0,  
		.noiscnt        = 0,   		
		.vnoictrl       = 0,  		
		.vnoifreq[0]    = 0, 
		.vnoifreq[1]    = 0, 
		.vnoifreq[2]    = 0, 
		.vnoifreq[3]    = 0, 
		.vnoifreq[4]    = 0, 
		.vnoitchapx[0]  = 0,  
		.vnoitchapx[1]  = 0,  
		.vnoitchapx[2]  = 0,  
		.vnoitchapx[3]  = 0,  
		.vnoitchapx[4]  = 0,  
		.vnoinotchapx[0]= 0, 
		.vnoinotchapx[1]= 0, 
		.vnoinotchapx[2]= 0, 
		.vnoinotchapx[3]= 0, 
		.vnoinotchapx[4]= 0, 
		.reserved_6     = 0,   	
		.vnoilonltdthr  = 0,  
		.reserved_7     = 0,   		
		.vnoicnt        = 0, 
		.blknltdthr  	= 0,
		.reserved_8  	= 0,
	},
	{
		.ctrl			= 0,
		.calcfg1		= 0,	
		.cfg1			= 0,
		.cfg2			= 0,
		.cfg3			= 0,
		.nlgain			= 0,
		.iircoeff		= 0,	
		.minnltddiff	= 0,
		.minnltdhop		= 0,
		.reserved		= 0,
		.reserved_1		= 0,
		.hopst			= 0,
		.stabctrl		= 0,
		.stabfreq[0]	= 0,
		.stabfreq[1]	= 0,
		.stabfreq[2]	= 0,
		.stabfreq[3]	= 0,
		.stabfreq[4]	= 0,
		.stabtchapx[0]	= 0,
		.stabtchapx[1]	= 0,
		.stabtchapx[2]	= 0,
		.stabtchapx[3]	= 0,
		.stabtchapx[4]	= 0,
		.stabnotchapx[0]= 0,
		.stabnotchapx[1]= 0,
		.stabnotchapx[2]= 0,
		.stabnotchapx[3]= 0,
		.stabnotchapx[4]= 0,
		.reserved_2		= 0,
		.reserved_3		= 0,
		.stabhinltdthr	= 0,
		.reserved_4		= 0,
		.noisctrl       = 0, 		
		.noisfreq[0]    = 0,  	
		.noisfreq[1]    = 0,  	
		.noisfreq[2]    = 0,  	
		.noisfreq[3]    = 0,  	
		.noisfreq[4]    = 0,  	
		.noistchapx[0]  = 0,  
		.noistchapx[1]  = 0,  
		.noistchapx[2]  = 0,  
		.noistchapx[3]  = 0,  
		.noistchapx[4]  = 0,  
		.noisnotchapx[0]= 0, 
		.noisnotchapx[1]= 0, 
		.noisnotchapx[2]= 0, 
		.noisnotchapx[3]= 0, 
		.noisnotchapx[4]= 0, 
		.reserved_5		= 0,
		.noislonltdthr  = 0,   
		.noishinltdthr  = 0,  
		.noiscnt        = 0,   		
		.vnoictrl       = 0,  		
		.vnoifreq[0]    = 0, 
		.vnoifreq[1]    = 0, 
		.vnoifreq[2]    = 0, 
		.vnoifreq[3]    = 0, 
		.vnoifreq[4]    = 0, 
		.vnoitchapx[0]  = 0,  
		.vnoitchapx[1]  = 0,  
		.vnoitchapx[2]  = 0,  
		.vnoitchapx[3]  = 0,  
		.vnoitchapx[4]  = 0,  
		.vnoinotchapx[0]= 0, 
		.vnoinotchapx[1]= 0, 
		.vnoinotchapx[2]= 0, 
		.vnoinotchapx[3]= 0, 
		.vnoinotchapx[4]= 0, 
		.reserved_6     = 0,   	
		.vnoilonltdthr  = 0,  
		.reserved_7     = 0,   		
		.vnoicnt        = 0, 
		.blknltdthr  	= 0,
		.reserved_8  	= 0,
	},
};

static spt_selfcapglobalconfig_t109_config_t obj_selfcapglobalconfig_t109[TOUCH_MODE_MAX_NUM] = {
	{
		.ctrl		= 2,
		.dbgctrl	= 0,
		.cmdonreset	= 5,
		.cmd		= 0,
		.lfcompsfx	= 0,
		.lfcompsfy	= 0,
		.reserved	= 0,
	},
	{
		.ctrl		= 2,
		.dbgctrl	= 0,
		.cmdonreset	= 5,
		.cmd		= 0,
		.lfcompsfx	= 0,
		.lfcompsfy	= 0,
		.reserved	= 0,
	},
	{
		.ctrl		= 2,
		.dbgctrl	= 0,
		.cmdonreset	= 5,
		.cmd		= 0,
		.lfcompsfx	= 0,
		.lfcompsfy	= 0,
		.reserved	= 0,
	},
	{
		.ctrl		= 2,
		.dbgctrl	= 0,
		.cmdonreset	= 5,
		.cmd		= 0,
		.lfcompsfx	= 0,
		.lfcompsfy	= 0,
		.reserved	= 0,
	},
};

#define T110_MAX_INSTANCE_SIZE		9
static spt_selfcaptuningparams_t110_config_t obj_selfcaptuningparams_t110[TOUCH_MODE_MAX_NUM][T110_MAX_INSTANCE_SIZE] = {
	{
		{
			.params[0]	= 1,
			.params[1]	= 193,
			.params[2]	= 969,
			.params[3]	= 945,
			.params[4]	= 929,
			.params[5]	= 961,
			.params[6]	= 929,
			.params[7]	= 1041,
			.params[8]	= 905,
			.params[9]	= 753,
			.params[10]	= 777,
			.params[11]	= 873,
			.params[12]	= 985,
			.params[13]	= 905,
			.params[14]	= 1025,
			.params[15]	= 969,
			.params[16]	= 953,
			.params[17]	= 1,
			.params[18]	= 1,
			.params[19]	= 1,
		},
		{
			.params[0]	= 1,
			.params[1]	= 2769,
			.params[2]	= 2633,
			.params[3]	= 2377,
			.params[4]	= 209,
			.params[5]	= 1,
			.params[6]	= 9,
			.params[7]	= 2265,
			.params[8]	= 3049,
			.params[9]	= 2769,
			.params[10]	= 3849,
			.params[11]	= 3681,
			.params[12]	= 3657,
			.params[13]	= 2657,
			.params[14]	= 2521,
			.params[15]	= 2265,
			.params[16]	= 2273,
			.params[17]	= 1,
			.params[18]	= 1,
			.params[19]	= 1,
		},
		{
			.params[0]	= 1,
			.params[1]	= 2545,
			.params[2]	= 2489,
			.params[3]	= 289,
			.params[4]	= 113,
			.params[5]	= 81,
			.params[6]	= 9,
			.params[7]	= 2201,
			.params[8]	= 3153,
			.params[9]	= 2489,
			.params[10]	= 3681,
			.params[11]	= 3537,
			.params[12]	= 2849,
			.params[13]	= 2521,
			.params[14]	= 2449,
			.params[15]	= 2201,
			.params[16]	= 3337,
			.params[17]	= 1,
			.params[18]	= 1,
			.params[19]	= 1,
		},
		{
			.params[0]	= 1,
			.params[1]	= 193,
			.params[2]	= 969,
			.params[3]	= 953,
			.params[4]	= 929,
			.params[5]	= 961,
			.params[6]	= 937,
			.params[7]	= 1041,
			.params[8]	= 905,
			.params[9]	= 761,
			.params[10]	= 793,
			.params[11]	= 881,
			.params[12]	= 993,
			.params[13]	= 913,
			.params[14]	= 1033,
			.params[15]	= 977,
			.params[16]	= 953,
			.params[17]	= 1,
			.params[18]	= 1,
			.params[19]	= 1,
		},
		{
			.params[0]	= 1,
			.params[1]	= 2785,
			.params[2]	= 2649,
			.params[3]	= 2393,
			.params[4]	= 225,
			.params[5]	= 1,
			.params[6]	= 25,
			.params[7]	= 2289,
			.params[8]	= 3073,
			.params[9]	= 2785,
			.params[10]	= 3849,
			.params[11]	= 3705,
			.params[12]	= 3689,
			.params[13]	= 2673,
			.params[14]	= 2545,
			.params[15]	= 2289,
			.params[16]	= 2297,
			.params[17]	= 1,
			.params[18]	= 1,
			.params[19]	= 1,
		},
		{
			.params[0]	= 1,
			.params[1]	= 2529,
			.params[2]	= 2473,
			.params[3]	= 281,
			.params[4]	= 97,
			.params[5]	= 73,
			.params[6]	= 1,
			.params[7]	= 2185,
			.params[8]	= 3137,
			.params[9]	= 2473,
			.params[10]	= 3681,
			.params[11]	= 3521,
			.params[12]	= 2833,
			.params[13]	= 2505,
			.params[14]	= 2433,
			.params[15]	= 2185,
			.params[16]	= 3329,
			.params[17]	= 1,
			.params[18]	= 1,
			.params[19]	= 1,
		},
		{
			.params[0]	= 4043,
			.params[1]	= 4043,
			.params[2]	= 4043,
			.params[3]	= 4043,
			.params[4]	= 4043,
			.params[5]	= 4043,
			.params[6]	= 4043,
			.params[7]	= 4043,
			.params[8]	= 4043,
			.params[9]	= 4043,
			.params[10]	= 4043,
			.params[11]	= 4043,
			.params[12]	= 4043,
			.params[13]	= 4043,
			.params[14]	= 4043,
			.params[15]	= 4043,
			.params[16]	= 4043,
			.params[17]	= 3,
			.params[18]	= 3,
			.params[19]	= 3,
		},
		{
			.params[0]	= 3,
			.params[1]	= 4043,
			.params[2]	= 4043,
			.params[3]	= 4043,
			.params[4]	= 4043,
			.params[5]	= 4043,
			.params[6]	= 4043,
			.params[7]	= 4043,
			.params[8]	= 4043,
			.params[9]	= 4043,
			.params[10]	= 4043,
			.params[11]	= 4043,
			.params[12]	= 4043,
			.params[13]	= 4043,
			.params[14]	= 4043,
			.params[15]	= 4043,
			.params[16]	= 4043,
			.params[17]	= 3,
			.params[18]	= 3,
			.params[19]	= 3,
		},
		{
			.params[0]	= 3,
			.params[1]	= 4043,
			.params[2]	= 4043,
			.params[3]	= 4043,
			.params[4]	= 4043,
			.params[5]	= 4043,
			.params[6]	= 4043,
			.params[7]	= 4043,
			.params[8]	= 4043,
			.params[9]	= 4043,
			.params[10]	= 4043,
			.params[11]	= 4043,
			.params[12]	= 4043,
			.params[13]	= 4043,
			.params[14]	= 4043,
			.params[15]	= 4043,
			.params[16]	= 4043,
			.params[17]	= 3,
			.params[18]	= 3,
			.params[19]	= 3,
		},
	},
	{
		{
			.params[0]	= 1,
			.params[1]	= 193,
			.params[2]	= 969,
			.params[3]	= 945,
			.params[4]	= 929,
			.params[5]	= 961,
			.params[6]	= 929,
			.params[7]	= 1041,
			.params[8]	= 905,
			.params[9]	= 753,
			.params[10]	= 777,
			.params[11]	= 873,
			.params[12]	= 985,
			.params[13]	= 905,
			.params[14]	= 1025,
			.params[15]	= 969,
			.params[16]	= 953,
			.params[17]	= 1,
			.params[18]	= 1,
			.params[19]	= 1,
		},
		{
			.params[0]	= 1,
			.params[1]	= 2769,
			.params[2]	= 2633,
			.params[3]	= 2377,
			.params[4]	= 209,
			.params[5]	= 1,
			.params[6]	= 9,
			.params[7]	= 2265,
			.params[8]	= 3049,
			.params[9]	= 2769,
			.params[10]	= 3849,
			.params[11]	= 3681,
			.params[12]	= 3657,
			.params[13]	= 2657,
			.params[14]	= 2521,
			.params[15]	= 2265,
			.params[16]	= 2273,
			.params[17]	= 1,
			.params[18]	= 1,
			.params[19]	= 1,
		},
		{
			.params[0]	= 1,
			.params[1]	= 2545,
			.params[2]	= 2489,
			.params[3]	= 289,
			.params[4]	= 113,
			.params[5]	= 81,
			.params[6]	= 9,
			.params[7]	= 2201,
			.params[8]	= 3153,
			.params[9]	= 2489,
			.params[10]	= 3681,
			.params[11]	= 3537,
			.params[12]	= 2849,
			.params[13]	= 2521,
			.params[14]	= 2449,
			.params[15]	= 2201,
			.params[16]	= 3337,
			.params[17]	= 1,
			.params[18]	= 1,
			.params[19]	= 1,
		},
		{
			.params[0]	= 1,
			.params[1]	= 193,
			.params[2]	= 969,
			.params[3]	= 953,
			.params[4]	= 929,
			.params[5]	= 961,
			.params[6]	= 937,
			.params[7]	= 1041,
			.params[8]	= 905,
			.params[9]	= 761,
			.params[10]	= 793,
			.params[11]	= 881,
			.params[12]	= 993,
			.params[13]	= 913,
			.params[14]	= 1033,
			.params[15]	= 977,
			.params[16]	= 953,
			.params[17]	= 1,
			.params[18]	= 1,
			.params[19]	= 1,
		},
		{
			.params[0]	= 1,
			.params[1]	= 2785,
			.params[2]	= 2649,
			.params[3]	= 2393,
			.params[4]	= 225,
			.params[5]	= 1,
			.params[6]	= 25,
			.params[7]	= 2289,
			.params[8]	= 3073,
			.params[9]	= 2785,
			.params[10]	= 3849,
			.params[11]	= 3705,
			.params[12]	= 3689,
			.params[13]	= 2673,
			.params[14]	= 2545,
			.params[15]	= 2289,
			.params[16]	= 2297,
			.params[17]	= 1,
			.params[18]	= 1,
			.params[19]	= 1,
		},
		{
			.params[0]	= 1,
			.params[1]	= 2529,
			.params[2]	= 2473,
			.params[3]	= 281,
			.params[4]	= 97,
			.params[5]	= 73,
			.params[6]	= 1,
			.params[7]	= 2185,
			.params[8]	= 3137,
			.params[9]	= 2473,
			.params[10]	= 3681,
			.params[11]	= 3521,
			.params[12]	= 2833,
			.params[13]	= 2505,
			.params[14]	= 2433,
			.params[15]	= 2185,
			.params[16]	= 3329,
			.params[17]	= 1,
			.params[18]	= 1,
			.params[19]	= 1,
		},
		{
			.params[0]	= 4043,
			.params[1]	= 4043,
			.params[2]	= 4043,
			.params[3]	= 4043,
			.params[4]	= 4043,
			.params[5]	= 4043,
			.params[6]	= 4043,
			.params[7]	= 4043,
			.params[8]	= 4043,
			.params[9]	= 4043,
			.params[10]	= 4043,
			.params[11]	= 4043,
			.params[12]	= 4043,
			.params[13]	= 4043,
			.params[14]	= 4043,
			.params[15]	= 4043,
			.params[16]	= 4043,
			.params[17]	= 3,
			.params[18]	= 3,
			.params[19]	= 3,
		},
		{
			.params[0]	= 3,
			.params[1]	= 4043,
			.params[2]	= 4043,
			.params[3]	= 4043,
			.params[4]	= 4043,
			.params[5]	= 4043,
			.params[6]	= 4043,
			.params[7]	= 4043,
			.params[8]	= 4043,
			.params[9]	= 4043,
			.params[10]	= 4043,
			.params[11]	= 4043,
			.params[12]	= 4043,
			.params[13]	= 4043,
			.params[14]	= 4043,
			.params[15]	= 4043,
			.params[16]	= 4043,
			.params[17]	= 3,
			.params[18]	= 3,
			.params[19]	= 3,
		},
		{
			.params[0]	= 3,
			.params[1]	= 4043,
			.params[2]	= 4043,
			.params[3]	= 4043,
			.params[4]	= 4043,
			.params[5]	= 4043,
			.params[6]	= 4043,
			.params[7]	= 4043,
			.params[8]	= 4043,
			.params[9]	= 4043,
			.params[10]	= 4043,
			.params[11]	= 4043,
			.params[12]	= 4043,
			.params[13]	= 4043,
			.params[14]	= 4043,
			.params[15]	= 4043,
			.params[16]	= 4043,
			.params[17]	= 3,
			.params[18]	= 3,
			.params[19]	= 3,
		},
	},
	{
		{
			.params[0]	= 1,
			.params[1]	= 193,
			.params[2]	= 969,
			.params[3]	= 945,
			.params[4]	= 929,
			.params[5]	= 961,
			.params[6]	= 929,
			.params[7]	= 1041,
			.params[8]	= 905,
			.params[9]	= 753,
			.params[10]	= 777,
			.params[11]	= 873,
			.params[12]	= 985,
			.params[13]	= 905,
			.params[14]	= 1025,
			.params[15]	= 969,
			.params[16]	= 953,
			.params[17]	= 1,
			.params[18]	= 1,
			.params[19]	= 1,
		},
		{
			.params[0]	= 1,
			.params[1]	= 2769,
			.params[2]	= 2633,
			.params[3]	= 2377,
			.params[4]	= 209,
			.params[5]	= 1,
			.params[6]	= 9,
			.params[7]	= 2265,
			.params[8]	= 3049,
			.params[9]	= 2769,
			.params[10]	= 3849,
			.params[11]	= 3681,
			.params[12]	= 3657,
			.params[13]	= 2657,
			.params[14]	= 2521,
			.params[15]	= 2265,
			.params[16]	= 2273,
			.params[17]	= 1,
			.params[18]	= 1,
			.params[19]	= 1,
		},
		{
			.params[0]	= 1,
			.params[1]	= 2545,
			.params[2]	= 2489,
			.params[3]	= 289,
			.params[4]	= 113,
			.params[5]	= 81,
			.params[6]	= 9,
			.params[7]	= 2201,
			.params[8]	= 3153,
			.params[9]	= 2489,
			.params[10]	= 3681,
			.params[11]	= 3537,
			.params[12]	= 2849,
			.params[13]	= 2521,
			.params[14]	= 2449,
			.params[15]	= 2201,
			.params[16]	= 3337,
			.params[17]	= 1,
			.params[18]	= 1,
			.params[19]	= 1,
		},
		{
			.params[0]	= 1,
			.params[1]	= 193,
			.params[2]	= 969,
			.params[3]	= 953,
			.params[4]	= 929,
			.params[5]	= 961,
			.params[6]	= 937,
			.params[7]	= 1041,
			.params[8]	= 905,
			.params[9]	= 761,
			.params[10]	= 793,
			.params[11]	= 881,
			.params[12]	= 993,
			.params[13]	= 913,
			.params[14]	= 1033,
			.params[15]	= 977,
			.params[16]	= 953,
			.params[17]	= 1,
			.params[18]	= 1,
			.params[19]	= 1,
		},
		{
			.params[0]	= 1,
			.params[1]	= 2785,
			.params[2]	= 2649,
			.params[3]	= 2393,
			.params[4]	= 225,
			.params[5]	= 1,
			.params[6]	= 25,
			.params[7]	= 2289,
			.params[8]	= 3073,
			.params[9]	= 2785,
			.params[10]	= 3849,
			.params[11]	= 3705,
			.params[12]	= 3689,
			.params[13]	= 2673,
			.params[14]	= 2545,
			.params[15]	= 2289,
			.params[16]	= 2297,
			.params[17]	= 1,
			.params[18]	= 1,
			.params[19]	= 1,
		},
		{
			.params[0]	= 1,
			.params[1]	= 2529,
			.params[2]	= 2473,
			.params[3]	= 281,
			.params[4]	= 97,
			.params[5]	= 73,
			.params[6]	= 1,
			.params[7]	= 2185,
			.params[8]	= 3137,
			.params[9]	= 2473,
			.params[10]	= 3681,
			.params[11]	= 3521,
			.params[12]	= 2833,
			.params[13]	= 2505,
			.params[14]	= 2433,
			.params[15]	= 2185,
			.params[16]	= 3329,
			.params[17]	= 1,
			.params[18]	= 1,
			.params[19]	= 1,
		},
		{
			.params[0]	= 4043,
			.params[1]	= 4043,
			.params[2]	= 4043,
			.params[3]	= 4043,
			.params[4]	= 4043,
			.params[5]	= 4043,
			.params[6]	= 4043,
			.params[7]	= 4043,
			.params[8]	= 4043,
			.params[9]	= 4043,
			.params[10]	= 4043,
			.params[11]	= 4043,
			.params[12]	= 4043,
			.params[13]	= 4043,
			.params[14]	= 4043,
			.params[15]	= 4043,
			.params[16]	= 4043,
			.params[17]	= 3,
			.params[18]	= 3,
			.params[19]	= 3,
		},
		{
			.params[0]	= 3,
			.params[1]	= 4043,
			.params[2]	= 4043,
			.params[3]	= 4043,
			.params[4]	= 4043,
			.params[5]	= 4043,
			.params[6]	= 4043,
			.params[7]	= 4043,
			.params[8]	= 4043,
			.params[9]	= 4043,
			.params[10]	= 4043,
			.params[11]	= 4043,
			.params[12]	= 4043,
			.params[13]	= 4043,
			.params[14]	= 4043,
			.params[15]	= 4043,
			.params[16]	= 4043,
			.params[17]	= 3,
			.params[18]	= 3,
			.params[19]	= 3,
		},
		{
			.params[0]	= 3,
			.params[1]	= 4043,
			.params[2]	= 4043,
			.params[3]	= 4043,
			.params[4]	= 4043,
			.params[5]	= 4043,
			.params[6]	= 4043,
			.params[7]	= 4043,
			.params[8]	= 4043,
			.params[9]	= 4043,
			.params[10]	= 4043,
			.params[11]	= 4043,
			.params[12]	= 4043,
			.params[13]	= 4043,
			.params[14]	= 4043,
			.params[15]	= 4043,
			.params[16]	= 4043,
			.params[17]	= 3,
			.params[18]	= 3,
			.params[19]	= 3,
		},
	},
	{
		{
			.params[0]	= 1,
			.params[1]	= 193,
			.params[2]	= 969,
			.params[3]	= 945,
			.params[4]	= 929,
			.params[5]	= 961,
			.params[6]	= 929,
			.params[7]	= 1041,
			.params[8]	= 905,
			.params[9]	= 753,
			.params[10]	= 777,
			.params[11]	= 873,
			.params[12]	= 985,
			.params[13]	= 905,
			.params[14]	= 1025,
			.params[15]	= 969,
			.params[16]	= 953,
			.params[17]	= 1,
			.params[18]	= 1,
			.params[19]	= 1,
		},
		{
			.params[0]	= 1,
			.params[1]	= 2769,
			.params[2]	= 2633,
			.params[3]	= 2377,
			.params[4]	= 209,
			.params[5]	= 1,
			.params[6]	= 9,
			.params[7]	= 2265,
			.params[8]	= 3049,
			.params[9]	= 2769,
			.params[10]	= 3849,
			.params[11]	= 3681,
			.params[12]	= 3657,
			.params[13]	= 2657,
			.params[14]	= 2521,
			.params[15]	= 2265,
			.params[16]	= 2273,
			.params[17]	= 1,
			.params[18]	= 1,
			.params[19]	= 1,
		},
		{
			.params[0]	= 1,
			.params[1]	= 2545,
			.params[2]	= 2489,
			.params[3]	= 289,
			.params[4]	= 113,
			.params[5]	= 81,
			.params[6]	= 9,
			.params[7]	= 2201,
			.params[8]	= 3153,
			.params[9]	= 2489,
			.params[10]	= 3681,
			.params[11]	= 3537,
			.params[12]	= 2849,
			.params[13]	= 2521,
			.params[14]	= 2449,
			.params[15]	= 2201,
			.params[16]	= 3337,
			.params[17]	= 1,
			.params[18]	= 1,
			.params[19]	= 1,
		},
		{
			.params[0]	= 1,
			.params[1]	= 193,
			.params[2]	= 969,
			.params[3]	= 953,
			.params[4]	= 929,
			.params[5]	= 961,
			.params[6]	= 937,
			.params[7]	= 1041,
			.params[8]	= 905,
			.params[9]	= 761,
			.params[10]	= 793,
			.params[11]	= 881,
			.params[12]	= 993,
			.params[13]	= 913,
			.params[14]	= 1033,
			.params[15]	= 977,
			.params[16]	= 953,
			.params[17]	= 1,
			.params[18]	= 1,
			.params[19]	= 1,
		},
		{
			.params[0]	= 1,
			.params[1]	= 2785,
			.params[2]	= 2649,
			.params[3]	= 2393,
			.params[4]	= 225,
			.params[5]	= 1,
			.params[6]	= 25,
			.params[7]	= 2289,
			.params[8]	= 3073,
			.params[9]	= 2785,
			.params[10]	= 3849,
			.params[11]	= 3705,
			.params[12]	= 3689,
			.params[13]	= 2673,
			.params[14]	= 2545,
			.params[15]	= 2289,
			.params[16]	= 2297,
			.params[17]	= 1,
			.params[18]	= 1,
			.params[19]	= 1,
		},
		{
			.params[0]	= 1,
			.params[1]	= 2529,
			.params[2]	= 2473,
			.params[3]	= 281,
			.params[4]	= 97,
			.params[5]	= 73,
			.params[6]	= 1,
			.params[7]	= 2185,
			.params[8]	= 3137,
			.params[9]	= 2473,
			.params[10]	= 3681,
			.params[11]	= 3521,
			.params[12]	= 2833,
			.params[13]	= 2505,
			.params[14]	= 2433,
			.params[15]	= 2185,
			.params[16]	= 3329,
			.params[17]	= 1,
			.params[18]	= 1,
			.params[19]	= 1,
		},
		{
			.params[0]	= 4043,
			.params[1]	= 4043,
			.params[2]	= 4043,
			.params[3]	= 4043,
			.params[4]	= 4043,
			.params[5]	= 4043,
			.params[6]	= 4043,
			.params[7]	= 4043,
			.params[8]	= 4043,
			.params[9]	= 4043,
			.params[10]	= 4043,
			.params[11]	= 4043,
			.params[12]	= 4043,
			.params[13]	= 4043,
			.params[14]	= 4043,
			.params[15]	= 4043,
			.params[16]	= 4043,
			.params[17]	= 3,
			.params[18]	= 3,
			.params[19]	= 3,
		},
		{
			.params[0]	= 3,
			.params[1]	= 4043,
			.params[2]	= 4043,
			.params[3]	= 4043,
			.params[4]	= 4043,
			.params[5]	= 4043,
			.params[6]	= 4043,
			.params[7]	= 4043,
			.params[8]	= 4043,
			.params[9]	= 4043,
			.params[10]	= 4043,
			.params[11]	= 4043,
			.params[12]	= 4043,
			.params[13]	= 4043,
			.params[14]	= 4043,
			.params[15]	= 4043,
			.params[16]	= 4043,
			.params[17]	= 3,
			.params[18]	= 3,
			.params[19]	= 3,
		},
		{
			.params[0]	= 3,
			.params[1]	= 4043,
			.params[2]	= 4043,
			.params[3]	= 4043,
			.params[4]	= 4043,
			.params[5]	= 4043,
			.params[6]	= 4043,
			.params[7]	= 4043,
			.params[8]	= 4043,
			.params[9]	= 4043,
			.params[10]	= 4043,
			.params[11]	= 4043,
			.params[12]	= 4043,
			.params[13]	= 4043,
			.params[14]	= 4043,
			.params[15]	= 4043,
			.params[16]	= 4043,
			.params[17]	= 3,
			.params[18]	= 3,
			.params[19]	= 3,
		},
	},
};

#define T111_MAX_INSTANCE_SIZE		3
static spt_selfcapconfig_t111_config_t obj_selfcapconfig_t111[TOUCH_MODE_MAX_NUM][T111_MAX_INSTANCE_SIZE] = {
	{
		{
			.ctrl         	= 8, 
			.dbgctrl	  	= 0,	 
			.inttime	  	= 70,	
			.delaytime	  	= 30,	
			.idlesyncsperl	= 24,	 
			.actvsyncsperl	= 24,	 
			.drift	  		= 5,	
			.driftst	  	= 5,
			.driftsthrsf  	= 0,
			.calecstr  		= 1,
			.filter  		= 12,
			.filtcfg  		= 0,
			.dyniirthru  	= 0,
			.dyniirthrl  	= 0,
			.dyniirclmp  	= 0,
			.rerserved  	= 0,
		},
		{
			.ctrl         	= 0, 
			.dbgctrl	  	= 0,	 
			.inttime	  	= 0,	
			.delaytime	  	= 0,	
			.idlesyncsperl	= 0,	 
			.actvsyncsperl	= 0,	 
			.drift	  		= 0,	
			.driftst	  	= 0,
			.driftsthrsf  	= 0,
			.calecstr  		= 0,
			.filter  		= 0,
			.filtcfg  		= 0,
			.dyniirthru  	= 0,
			.dyniirthrl  	= 0,
			.dyniirclmp  	= 0,
			.rerserved  	= 0,
		},
		{
			.ctrl         	= 8, 
			.dbgctrl	  	= 0,	 
			.inttime	  	= 70,	
			.delaytime	  	= 55,	
			.idlesyncsperl	= 24,	 
			.actvsyncsperl	= 24,	 
			.drift	  		= 8,	
			.driftst	  	= 10,
			.driftsthrsf  	= 0,
			.calecstr  		= 30,
			.filter  		= 12,
			.filtcfg  		= 0,
			.dyniirthru  	= 0,
			.dyniirthrl  	= 0,
			.dyniirclmp  	= 0,
			.rerserved  	= 0,
		},
	},
	{
		{
			.ctrl         	= 8, 
			.dbgctrl	  	= 0,	 
			.inttime	  	= 70,	
			.delaytime	  	= 30,	
			.idlesyncsperl	= 24,	 
			.actvsyncsperl	= 24,	 
			.drift	  		= 5,	
			.driftst	  	= 5,
			.driftsthrsf  	= 0,
			.calecstr  		= 1,
			.filter  		= 12,
			.filtcfg  		= 0,
			.dyniirthru  	= 0,
			.dyniirthrl  	= 0,
			.dyniirclmp  	= 0,
			.rerserved  	= 0,
		},
		{
			.ctrl         	= 0, 
			.dbgctrl	  	= 0,	 
			.inttime	  	= 0,	
			.delaytime	  	= 0,	
			.idlesyncsperl	= 0,	 
			.actvsyncsperl	= 0,	 
			.drift	  		= 0,	
			.driftst	  	= 0,
			.driftsthrsf  	= 0,
			.calecstr  		= 0,
			.filter  		= 0,
			.filtcfg  		= 0,
			.dyniirthru  	= 0,
			.dyniirthrl  	= 0,
			.dyniirclmp  	= 0,
			.rerserved  	= 0,
		},
		{
			.ctrl         	= 8, 
			.dbgctrl	  	= 0,	 
			.inttime	  	= 70,	
			.delaytime	  	= 55,	
			.idlesyncsperl	= 24,	 
			.actvsyncsperl	= 24,	 
			.drift	  		= 8,	
			.driftst	  	= 10,
			.driftsthrsf  	= 0,
			.calecstr  		= 30,
			.filter  		= 12,
			.filtcfg  		= 0,
			.dyniirthru  	= 0,
			.dyniirthrl  	= 0,
			.dyniirclmp  	= 0,
			.rerserved  	= 0,
		},
	},
	{
		{
			.ctrl         	= 8, 
			.dbgctrl	  	= 0,	 
			.inttime	  	= 70,	
			.delaytime	  	= 30,	
			.idlesyncsperl	= 24,	 
			.actvsyncsperl	= 24,	 
			.drift	  		= 5,	
			.driftst	  	= 5,
			.driftsthrsf  	= 0,
			.calecstr  		= 5,
			.filter  		= 12,
			.filtcfg  		= 0,
			.dyniirthru  	= 0,
			.dyniirthrl  	= 0,
			.dyniirclmp  	= 0,
			.rerserved  	= 0,
		},
		{
			.ctrl         	= 0, 
			.dbgctrl	  	= 0,	 
			.inttime	  	= 0,	
			.delaytime	  	= 0,	
			.idlesyncsperl	= 0,	 
			.actvsyncsperl	= 0,	 
			.drift	  		= 0,	
			.driftst	  	= 0,
			.driftsthrsf  	= 0,
			.calecstr  		= 0,
			.filter  		= 0,
			.filtcfg  		= 0,
			.dyniirthru  	= 0,
			.dyniirthrl  	= 0,
			.dyniirclmp  	= 0,
			.rerserved  	= 0,
		},
		{
			.ctrl         	= 8, 
			.dbgctrl	  	= 0,	 
			.inttime	  	= 70,	
			.delaytime	  	= 55,	
			.idlesyncsperl	= 24,	 
			.actvsyncsperl	= 24,	 
			.drift	  		= 8,	
			.driftst	  	= 10,
			.driftsthrsf  	= 0,
			.calecstr  		= 30,
			.filter  		= 12,
			.filtcfg  		= 0,
			.dyniirthru  	= 0,
			.dyniirthrl  	= 0,
			.dyniirclmp  	= 0,
			.rerserved  	= 0,
		},
	},
	{
		{
			.ctrl         	= 8, 
			.dbgctrl	  	= 0,	 
			.inttime	  	= 70,	
			.delaytime	  	= 30,	
			.idlesyncsperl	= 24,	 
			.actvsyncsperl	= 24,	 
			.drift	  		= 5,	
			.driftst	  	= 5,
			.driftsthrsf  	= 0,
			.calecstr  		= 5,
			.filter  		= 12,
			.filtcfg  		= 0,
			.dyniirthru  	= 0,
			.dyniirthrl  	= 0,
			.dyniirclmp  	= 0,
			.rerserved  	= 0,
		},
		{
			.ctrl         	= 0, 
			.dbgctrl	  	= 0,	 
			.inttime	  	= 0,	
			.delaytime	  	= 0,	
			.idlesyncsperl	= 0,	 
			.actvsyncsperl	= 0,	 
			.drift	  		= 0,	
			.driftst	  	= 0,
			.driftsthrsf  	= 0,
			.calecstr  		= 0,
			.filter  		= 0,
			.filtcfg  		= 0,
			.dyniirthru  	= 0,
			.dyniirthrl  	= 0,
			.dyniirclmp  	= 0,
			.rerserved  	= 0,
		},
		{
			.ctrl         	= 8, 
			.dbgctrl	  	= 0,	 
			.inttime	  	= 70,	
			.delaytime	  	= 55,	
			.idlesyncsperl	= 24,	 
			.actvsyncsperl	= 24,	 
			.drift	  		= 8,	
			.driftst	  	= 10,
			.driftsthrsf  	= 0,
			.calecstr  		= 30,
			.filter  		= 12,
			.filtcfg  		= 0,
			.dyniirthru  	= 0,
			.dyniirthrl  	= 0,
			.dyniirclmp  	= 0,
			.rerserved  	= 0,
		},
	},
};

static spt_proxmeasureconfig_t113_config_t obj_proxmeasureconfig_t113[TOUCH_MODE_MAX_NUM] = {
	{
		.ctrl    	= 0, 					
		.gainx 		= 9,          	
		.reserved 	= 9,         	
	},
	{
		.ctrl    	= 0, 					
		.gainx 		= 9,          	
		.reserved 	= 9,         	
	},
	{
		.ctrl    	= 0, 					
		.gainx 		= 9,          	
		.reserved 	= 9,         	
	},
	{
		.ctrl    	= 0, 					
		.gainx 		= 9,          	
		.reserved 	= 9,         	
	},
};

#endif //_EF67_MXT_CFG_
