ccflags-y += -Idrivers/media/platform/msm/camera_v2-ef71
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ef71/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ef71/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-ef71/common
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
